In [194]:
import pandas as pd

In [195]:
clubelo = pd.read_csv("data/clubelo.csv")
fbref2024 = pd.read_csv("data/fbref_games2024.csv")
fbref2025 = pd.read_csv("data/fbref_games2025.csv")
fbref_team2024 = pd.read_csv("data/fbref_team_season_stats2024.csv")
fbref_team2025 = pd.read_csv("data/fbref_team_season_stats2025.csv")
meteo = pd.read_csv("data/historique_meteo.csv")
managers = pd.read_csv("data/managers.csv")
pl_events = pd.read_csv("data/pl_events.csv")
fdcu2024 = pd.read_csv("data/pl_fdcu24_25.csv")
fdcu2025 = pd.read_csv("data/pl_fdcu25_26.csv")
referees = pd.read_csv("data/referees.csv")

## Clubelo

In [196]:
clubelo.head()

   Rank     Club Country  Level          Elo        From          To
0   4.0  Arsenal     ENG      1  1949.485474  2024-08-18  2024-08-22
1   4.0  Arsenal     ENG      1  1949.749512  2024-08-23  2024-08-24
2   4.0  Arsenal     ENG      1  1956.878906  2024-08-25  2024-08-29
3   3.0  Arsenal     ENG      1  1956.935181  2024-08-30  2024-08-30
4   4.0  Arsenal     ENG      1  1956.935181  2024-08-31  2024-08-31

In [197]:
clubelo.columns.tolist()

['Rank', 'Club', 'Country', 'Level', 'Elo', 'From', 'To']

In [198]:
clubelo = clubelo[["Club", "Elo", "From", "To"]]

In [199]:
clubelo.head()

      Club          Elo        From          To
0  Arsenal  1949.485474  2024-08-18  2024-08-22
1  Arsenal  1949.749512  2024-08-23  2024-08-24
2  Arsenal  1956.878906  2024-08-25  2024-08-29
3  Arsenal  1956.935181  2024-08-30  2024-08-30
4  Arsenal  1956.935181  2024-08-31  2024-08-31

## Fbref

In [200]:
fbref = pd.concat([fbref2024, fbref2025], ignore_index=True)

In [201]:
fbref.columns.tolist()

['week',
 'day',
 'date',
 'time',
 'home_team',
 'score',
 'away_team',
 'attendance',
 'venue',
 'referee',
 'match_report',
 'notes',
 'game_id']

In [202]:
fbref = fbref[["home_team", "away_team", "attendance", "referee", "venue", "game_id", "date"]]

In [203]:
print(fbref.shape)
fbref.head()

(760, 7)

,home_team,away_team,attendance,referee,venue,game_id,date
0,Manchester Utd,Fulham,73297.0,Robert Jones,Old Trafford,cc5b4244,2024-08-16
1,Arsenal,Wolves,60261.0,Jarred Gillett,Emirates Stadium,c0e3342a,2024-08-17
2,Everton,Brighton,39217.0,Simon Hooper,Goodison Park,71618ace,2024-08-17
3,Ipswich Town,Liverpool,30014.0,Tim Robinson,Portman Road Stadium,a1d0d529,2024-08-17
4,Newcastle United,Southampton,52196.0,Craig Pawson,St James' Park,34557647,2024-08-17

## Football Data UK

In [204]:
fdcu = pd.concat([fdcu2024, fdcu2025], ignore_index=True)

In [205]:
fdcu2024.columns.tolist()

['Div',
 'Date',
 'Time',
 'HomeTeam',
 'AwayTeam',
 'FTHG',
 'FTAG',
 'FTR',
 'HTHG',
 'HTAG',
 'HTR',
 'Referee',
 'HS',
 'AS',
 'HST',
 'AST',
 'HF',
 'AF',
 'HC',
 'AC',
 'HY',
 'AY',
 'HR',
 'AR',
 'B365H',
 'B365D',
 'B365A',
 'BWH',
 'BWD',
 'BWA',
 'BFH',
 'BFD',
 'BFA',
 'PSH',
 'PSD',
 'PSA',
 'WHH',
 'WHD',
 'WHA',
 '1XBH',
 '1XBD',
 '1XBA',
 'MaxH',
 'MaxD',
 'MaxA',
 'AvgH',
 'AvgD',
 'AvgA',
 'BFEH',
 'BFED',
 'BFEA',
 'B365>2.5',
 'B365<2.5',
 'P>2.5',
 'P<2.5',
 'Max>2.5',
 'Max<2.5',
 'Avg>2.5',
 'Avg<2.5',
 'BFE>2.5',
 'BFE<2.5',
 'AHh',
 'B365AHH',
 'B365AHA',
 'PAHH',
 'PAHA',
 'MaxAHH',
 'MaxAHA',
 'AvgAHH',
 'AvgAHA',
 'BFEAHH',
 'BFEAHA',
 'B365CH',
 'B365CD',
 'B365CA',
 'BWCH',
 'BWCD',
 'BWCA',
 'BFCH',
 'BFCD',
 'BFCA',
 'PSCH',
 'PSCD',
 'PSCA',
 'WHCH',
 'WHCD',
 'WHCA',
 '1XBCH',
 '1XBCD',
 '1XBCA',
 'MaxCH',
 'MaxCD',
 'MaxCA',
 'AvgCH',
 'AvgCD',
 'AvgCA',
 'BFECH',
 'BFECD',
 'BFECA',
 'B365C>2.5',
 'B365C<2.5',
 'PC>2.5',
 'PC<2.5',
 'MaxC>2.5',
 'MaxC<2.5',
 'AvgC>2.5',
 'AvgC<2.5',
 'BFEC>2.5',
 'BFEC<2.5',
 'AHCh',
 'B365CAHH',
 'B365CAHA',
 'PCAHH',
 'PCAHA',
 'MaxCAHH',
 'MaxCAHA',
 'AvgCAHH',
 'AvgCAHA',
 'BFECAHH',
 'BFECAHA']

In [206]:
fdcu = fdcu.drop(columns=['Div', 'Time'])

In [207]:
fdcu.head()

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,...,BMGMCA,BVCH,BVCD,BVCA,CLCH,CLCD,CLCA,LBCH,LBCD,LBCA
0,16/08/2024,Man United,Fulham,1,0,H,0,0,D,R Jones,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,17/08/2024,Ipswich,Liverpool,0,2,A,0,0,D,T Robinson,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,17/08/2024,Arsenal,Wolves,2,0,H,1,0,H,J Gillett,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,17/08/2024,Everton,Brighton,0,3,A,0,1,A,S Hooper,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,17/08/2024,Newcastle,Southampton,1,0,H,1,0,H,C Pawson,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [208]:
fdcu = fdcu[[col for col in fdcu.columns if not col.startswith(('B365', 'BW', 'BF', 'WH', '1XB'))]]

In [209]:
print(fdcu.shape)
fdcu.head()

(718, 90)

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,...,BMGMCA,BVCH,BVCD,BVCA,CLCH,CLCD,CLCA,LBCH,LBCD,LBCA
0,16/08/2024,Man United,Fulham,1,0,H,0,0,D,R Jones,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,17/08/2024,Ipswich,Liverpool,0,2,A,0,0,D,T Robinson,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,17/08/2024,Arsenal,Wolves,2,0,H,1,0,H,J Gillett,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,17/08/2024,Everton,Brighton,0,3,A,0,1,A,S Hooper,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,17/08/2024,Newcastle,Southampton,1,0,H,1,0,H,C Pawson,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [210]:
fdcu['Date'] = pd.to_datetime(fdcu['Date'], format='%d/%m/%Y')
fdcu['Date'] = fdcu['Date'].dt.strftime('%Y-%m-%d')

In [211]:
fdcu.head()

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,...,BMGMCA,BVCH,BVCD,BVCA,CLCH,CLCD,CLCA,LBCH,LBCD,LBCA
0,2024-08-16,Man United,Fulham,1,0,H,0,0,D,R Jones,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-08-17,Ipswich,Liverpool,0,2,A,0,0,D,T Robinson,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-08-17,Arsenal,Wolves,2,0,H,1,0,H,J Gillett,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-08-17,Everton,Brighton,0,3,A,0,1,A,S Hooper,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-08-17,Newcastle,Southampton,1,0,H,1,0,H,C Pawson,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## BSD

In [212]:
pl_events.columns.tolist()

['id',
 'home_team',
 'away_team',
 'event_date',
 'round_number',
 'group_name',
 'status',
 'home_score',
 'away_score',
 'home_score_ht',
 'away_score_ht',
 'current_minute',
 'period',
 'odds_home',
 'odds_draw',
 'odds_away',
 'odds_over_15',
 'odds_over_25',
 'odds_over_35',
 'odds_under_15',
 'odds_under_25',
 'odds_under_35',
 'odds_btts_yes',
 'odds_btts_no',
 'actual_home_xg',
 'actual_away_xg',
 'home_xg_live',
 'away_xg_live',
 'penalty_shootout',
 'unavailable_players',
 'incidents',
 'live_stats',
 'lineups',
 'shotmap',
 'momentum',
 'xg_per_minute',
 'average_positions',
 'ai_preview',
 'league_id',
 'league_name',
 'league_slug',
 'season_id',
 'season_name',
 'season_year',
 'home_team_obj_id',
 'home_team_obj_name',
 'home_team_obj_short_name',
 'away_team_obj_id',
 'away_team_obj_name',
 'away_team_obj_short_name',
 'home_coach_id',
 'home_coach_name',
 'away_coach_id',
 'away_coach_name',
 'referee_id',
 'referee_name',
 'venue_id',
 'venue_name',
 'venue_city',
 'venue_capacity']

In [213]:
pl_events.head()

,id,home_team,away_team,event_date,round_number,group_name,status,home_score,away_score,home_score_ht,...,home_coach_id,home_coach_name,away_coach_id,away_coach_name,referee_id,referee_name,venue_id,venue_name,venue_city,venue_capacity
0,160173,Manchester United,Fulham,2024-08-16T20:00:00+04:00,1,NaN,finished,1.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,17,Old Trafford,Manchester,74879
1,160174,Ipswich Town,Liverpool,2024-08-17T12:30:00+04:00,1,NaN,finished,0.0,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,195,Portman Road Stadium,Ipswich,29673
2,160178,Nottingham Forest,Bournemouth,2024-08-17T15:00:00+04:00,1,NaN,finished,1.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,15,City Ground,Nottingham,30445
3,160175,Arsenal,Bolton Wanderers,2024-08-17T15:00:00+04:00,1,NaN,finished,2.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,18,Emirates Stadium,London,60704
4,160176,Everton,Brighton & Hove Albion,2024-08-17T15:00:00+04:00,1,NaN,finished,0.0,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,20,Hill Dickinson Stadium,Liverpool,52888

In [214]:
pl_events = pl_events[pl_events["status"] == "finished"]

In [215]:
pl_events.head()

,id,home_team,away_team,event_date,round_number,group_name,status,home_score,away_score,home_score_ht,...,home_coach_id,home_coach_name,away_coach_id,away_coach_name,referee_id,referee_name,venue_id,venue_name,venue_city,venue_capacity
0,160173,Manchester United,Fulham,2024-08-16T20:00:00+04:00,1,NaN,finished,1.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,17,Old Trafford,Manchester,74879
1,160174,Ipswich Town,Liverpool,2024-08-17T12:30:00+04:00,1,NaN,finished,0.0,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,195,Portman Road Stadium,Ipswich,29673
2,160178,Nottingham Forest,Bournemouth,2024-08-17T15:00:00+04:00,1,NaN,finished,1.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,15,City Ground,Nottingham,30445
3,160175,Arsenal,Bolton Wanderers,2024-08-17T15:00:00+04:00,1,NaN,finished,2.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,18,Emirates Stadium,London,60704
4,160176,Everton,Brighton & Hove Albion,2024-08-17T15:00:00+04:00,1,NaN,finished,0.0,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,20,Hill Dickinson Stadium,Liverpool,52888

In [216]:
pl_events = pl_events[['id',
 'home_team',
 'away_team',
 'event_date',
 'home_score',
 'away_score',
 'actual_home_xg',
 'actual_away_xg',
 'home_team_obj_id',
 'away_team_obj_id',
 'home_coach_id',
 'home_coach_name',
 'away_coach_id',
 'away_coach_name',
 'referee_id',
 'referee_name',
 'venue_id',
 'venue_name',
 'venue_city',
                              ]]

In [217]:
print(pl_events.shape)
pl_events.head()

(719, 19)

,id,home_team,away_team,event_date,home_score,away_score,actual_home_xg,actual_away_xg,home_team_obj_id,away_team_obj_id,home_coach_id,home_coach_name,away_coach_id,away_coach_name,referee_id,referee_name,venue_id,venue_name,venue_city
0,160173,Manchester United,Fulham,2024-08-16T20:00:00+04:00,1.0,0.0,NaN,NaN,17,6,NaN,NaN,NaN,NaN,NaN,NaN,17,Old Trafford,Manchester
1,160174,Ipswich Town,Liverpool,2024-08-17T12:30:00+04:00,0.0,2.0,NaN,NaN,200,1,NaN,NaN,NaN,NaN,NaN,NaN,195,Portman Road Stadium,Ipswich
2,160178,Nottingham Forest,Bournemouth,2024-08-17T15:00:00+04:00,1.0,1.0,NaN,NaN,15,2,NaN,NaN,NaN,NaN,NaN,NaN,15,City Ground,Nottingham
3,160175,Arsenal,Bolton Wanderers,2024-08-17T15:00:00+04:00,2.0,0.0,NaN,NaN,18,1247,NaN,NaN,NaN,NaN,NaN,NaN,18,Emirates Stadium,London
4,160176,Everton,Brighton & Hove Albion,2024-08-17T15:00:00+04:00,0.0,3.0,NaN,NaN,20,5,NaN,NaN,NaN,NaN,NaN,NaN,20,Hill Dickinson Stadium,Liverpool

In [218]:
pl_events['event_date'] = pd.to_datetime(pl_events['event_date'])
pl_events['event_date'] = pl_events['event_date'].dt.strftime('%Y-%m-%d')

In [219]:
pl_events.head()

,id,home_team,away_team,event_date,home_score,away_score,actual_home_xg,actual_away_xg,home_team_obj_id,away_team_obj_id,home_coach_id,home_coach_name,away_coach_id,away_coach_name,referee_id,referee_name,venue_id,venue_name,venue_city
0,160173,Manchester United,Fulham,2024-08-16,1.0,0.0,NaN,NaN,17,6,NaN,NaN,NaN,NaN,NaN,NaN,17,Old Trafford,Manchester
1,160174,Ipswich Town,Liverpool,2024-08-17,0.0,2.0,NaN,NaN,200,1,NaN,NaN,NaN,NaN,NaN,NaN,195,Portman Road Stadium,Ipswich
2,160178,Nottingham Forest,Bournemouth,2024-08-17,1.0,1.0,NaN,NaN,15,2,NaN,NaN,NaN,NaN,NaN,NaN,15,City Ground,Nottingham
3,160175,Arsenal,Bolton Wanderers,2024-08-17,2.0,0.0,NaN,NaN,18,1247,NaN,NaN,NaN,NaN,NaN,NaN,18,Emirates Stadium,London
4,160176,Everton,Brighton & Hove Albion,2024-08-17,0.0,3.0,NaN,NaN,20,5,NaN,NaN,NaN,NaN,NaN,NaN,20,Hill Dickinson Stadium,Liverpool

## FBref Team Stats

In [220]:
fbref_team2024.columns.tolist()

['players_used',
 'Age',
 'Poss',
 'Playing Time',
 'Playing Time.1',
 'Playing Time.2',
 'Playing Time.3',
 'Performance',
 'Performance.1',
 'Performance.2',
 'Performance.3',
 'Performance.4',
 'Performance.5',
 'Performance.6',
 'Performance.7',
 'Per 90 Minutes',
 'Per 90 Minutes.1',
 'Per 90 Minutes.2',
 'Per 90 Minutes.3',
 'Per 90 Minutes.4',
 'url']

In [221]:
fbref_team2024.head()

,players_used,Age,Poss,Playing Time,Playing Time.1,Playing Time.2,Playing Time.3,Performance,Performance.1,Performance.2,...,Performance.4,Performance.5,Performance.6,Performance.7,Per 90 Minutes,Per 90 Minutes.1,Per 90 Minutes.2,Per 90 Minutes.3,Per 90 Minutes.4,url
0,NaN,NaN,NaN,MP,Starts,Min,90s,Gls,Ast,G+A,...,PK,PKatt,CrdY,CrdR,Gls,Ast,G+A,G-PK,G+A-PK,NaN
1,25.0,25.8,56.9,38,418,3420,38,67,55,122,...,2,2,70,6,1.76,1.45,3.21,1.71,3.16,/en/squads/18bb7c10/2024-2025/Arsenal-Stats
2,28.0,27.0,50.5,38,418,3420,38,56,45,101,...,3,6,76,4,1.47,1.18,2.66,1.39,2.58,/en/squads/8602292d/2024-2025/Aston-Villa-Stats
3,29.0,25.1,48.5,38,418,3420,38,57,41,98,...,6,7,97,3,1.5,1.08,2.58,1.34,2.42,/en/squads/4ba7cbea/2024-2025/Bournemouth-Stats
4,28.0,25.8,47.9,38,418,3420,38,65,44,109,...,5,6,62,1,1.71,1.16,2.87,1.58,2.74,/en/squads/cd051869/2024-2025/Brentford-Stats

In [222]:
def process_fbref_team_data(df):
    """
    Pipeline complète : Renommage, Extraction du club, Sélection et 
    Normalisation des statistiques (division par 38).
    """
    
    # 1. Renommage des colonnes (Fusion des deux niveaux d'en-tête)
    nouveaux_noms = []
    for nom_colonne, sous_categorie in zip(df.columns, df.iloc[0]):
        # On retire le suffixe .1, .2 ajouté par pandas
        nom_principal = nom_colonne.split('.')[0] 
        
        if pd.isna(sous_categorie):
            nouveaux_noms.append(nom_principal)
        else:
            nouveaux_noms.append(f"{nom_principal}_{sous_categorie}")
            
    df.columns = nouveaux_noms

    # 2. Suppression de la ligne 0 (sous-catégories) et reset de l'index
    df = df.iloc[1:].reset_index(drop=True)

    # 3. Extraction du nom du club depuis la colonne 'url'
    # Logique : on prend la partie après le dernier '/', puis on retire '-Stats'
    if 'url' in df.columns:
        df['club'] = df['url'].str.split('/').str[-1].str.replace('-Stats', '', regex=False)

    # 4. Sélection des colonnes cibles
    # Note : On inclut 'club' dans la sélection
    colonnes_a_garder = [
        "club", "players_used", "Age", "Poss", 
        "Per 90 Minutes_Gls", "Per 90 Minutes_Ast", 
        "Performance_PK", "Performance_PKatt", 
        "Performance_CrdY", "Performance_CrdR"
    ]
    
    # On filtre en vérifiant que les colonnes existent bien
    df = df[[c for c in colonnes_a_garder if c in df.columns]].copy()

    # 5. Conversion en numérique et division par 38
    # On cible les PK et les Cartons (CrdY et CrdR)
    cols_a_transformer = [
        'Performance_PK', 'Performance_PKatt', 
        'Performance_CrdY', 'Performance_CrdR'
    ]
    
    for col in cols_a_transformer:
        if col in df.columns:
            # On force la conversion en nombre avant de diviser
            df[col] = pd.to_numeric(df[col], errors='coerce') / 38
            
    return df

# --- Utilisation ---
fbref_team2024 = process_fbref_team_data(fbref_team2024)
fbref_team2025 = process_fbref_team_data(fbref_team2025)
fbref_team2024["season"] = "2024-2025"
fbref_team2025["season"] = "2025-2026"

In [223]:
fbref_team = pd.concat([fbref_team2024, fbref_team2025], ignore_index = True)

In [224]:
fbref_team.head()

,club,players_used,Age,Poss,Per 90 Minutes_Gls,Per 90 Minutes_Ast,Performance_PK,Performance_PKatt,Performance_CrdY,Performance_CrdR,season
0,Arsenal,25.0,25.8,56.9,1.76,1.45,0.052632,0.052632,1.842105,0.157895,2024-2025
1,Aston-Villa,28.0,27.0,50.5,1.47,1.18,0.078947,0.157895,2.000000,0.105263,2024-2025
2,Bournemouth,29.0,25.1,48.5,1.5,1.08,0.157895,0.184211,2.552632,0.078947,2024-2025
3,Brentford,28.0,25.8,47.9,1.71,1.16,0.131579,0.157895,1.631579,0.026316,2024-2025
4,Brighton-and-Hove-Albion,32.0,24.8,52.3,1.68,1.08,0.184211,0.184211,2.052632,0.078947,2024-2025

## Merge all stats

In [225]:
fbref.head()

,home_team,away_team,attendance,referee,venue,game_id,date
0,Manchester Utd,Fulham,73297.0,Robert Jones,Old Trafford,cc5b4244,2024-08-16
1,Arsenal,Wolves,60261.0,Jarred Gillett,Emirates Stadium,c0e3342a,2024-08-17
2,Everton,Brighton,39217.0,Simon Hooper,Goodison Park,71618ace,2024-08-17
3,Ipswich Town,Liverpool,30014.0,Tim Robinson,Portman Road Stadium,a1d0d529,2024-08-17
4,Newcastle United,Southampton,52196.0,Craig Pawson,St James' Park,34557647,2024-08-17

In [228]:
fbref["home_team"].unique()

<StringArray>
[   'Manchester Utd',           'Arsenal',           'Everton',
      'Ipswich Town',  'Newcastle United', 'Nottingham Forest',
   'West Ham United',         'Brentford',           'Chelsea',
    'Leicester City',       'Aston Villa',          'Brighton',
    'Crystal Palace',            'Fulham',   'Manchester City',
       'Southampton', 'Tottenham Hotspur',       'Bournemouth',
         'Liverpool',            'Wolves',        'Sunderland',
      'Leeds United',           'Burnley']
Length: 23, dtype: str

In [226]:
pl_events.head()

,id,home_team,away_team,event_date,home_score,away_score,actual_home_xg,actual_away_xg,home_team_obj_id,away_team_obj_id,home_coach_id,home_coach_name,away_coach_id,away_coach_name,referee_id,referee_name,venue_id,venue_name,venue_city
0,160173,Manchester United,Fulham,2024-08-16,1.0,0.0,NaN,NaN,17,6,NaN,NaN,NaN,NaN,NaN,NaN,17,Old Trafford,Manchester
1,160174,Ipswich Town,Liverpool,2024-08-17,0.0,2.0,NaN,NaN,200,1,NaN,NaN,NaN,NaN,NaN,NaN,195,Portman Road Stadium,Ipswich
2,160178,Nottingham Forest,Bournemouth,2024-08-17,1.0,1.0,NaN,NaN,15,2,NaN,NaN,NaN,NaN,NaN,NaN,15,City Ground,Nottingham
3,160175,Arsenal,Bolton Wanderers,2024-08-17,2.0,0.0,NaN,NaN,18,1247,NaN,NaN,NaN,NaN,NaN,NaN,18,Emirates Stadium,London
4,160176,Everton,Brighton & Hove Albion,2024-08-17,0.0,3.0,NaN,NaN,20,5,NaN,NaN,NaN,NaN,NaN,NaN,20,Hill Dickinson Stadium,Liverpool

In [229]:
pl_events["home_team"].unique()

<StringArray>
[     'Manchester United',           'Ipswich Town',      'Nottingham Forest',
                'Arsenal',                'Everton',       'Newcastle United',
        'West Ham United',              'Brentford',                'Chelsea',
         'Leicester City', 'Brighton & Hove Albion',      'Tottenham Hotspur',
        'Manchester City',         'Crystal Palace',            'Southampton',
                 'Fulham',            'Aston Villa',            'Bournemouth',
       'Bolton Wanderers',              'Liverpool',             'Sunderland',
          'Wolverhampton',           'Leeds United',                'Burnley']
Length: 24, dtype: str

In [227]:
fdcu.head()

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,...,BMGMCA,BVCH,BVCD,BVCA,CLCH,CLCD,CLCA,LBCH,LBCD,LBCA
0,2024-08-16,Man United,Fulham,1,0,H,0,0,D,R Jones,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-08-17,Ipswich,Liverpool,0,2,A,0,0,D,T Robinson,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-08-17,Arsenal,Wolves,2,0,H,1,0,H,J Gillett,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-08-17,Everton,Brighton,0,3,A,0,1,A,S Hooper,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-08-17,Newcastle,Southampton,1,0,H,1,0,H,C Pawson,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [231]:
fdcu["HomeTeam"].unique()

<StringArray>
[    'Man United',        'Ipswich',        'Arsenal',        'Everton',
      'Newcastle',  'Nott'm Forest',       'West Ham',      'Brentford',
        'Chelsea',      'Leicester',       'Brighton', 'Crystal Palace',
         'Fulham',       'Man City',    'Southampton',      'Tottenham',
    'Aston Villa',    'Bournemouth',         'Wolves',      'Liverpool',
     'Sunderland',          'Leeds',        'Burnley']
Length: 23, dtype: str

In [236]:
# ---------------------------------------------------------
# ÉTAPE 0 : Correction des anomalies dans la source pl_events
# ---------------------------------------------------------
pl_events['home_team'] = pl_events['home_team'].replace({'Bolton Wanderers': 'Wolverhampton'})
pl_events['away_team'] = pl_events['away_team'].replace({'Bolton Wanderers': 'Wolverhampton'})

# ---------------------------------------------------------
# ÉTAPE 1 : Uniformiser les colonnes de jointure
# On s'assure d'avoir 'home_team', 'away_team' et 'date' partout
# ---------------------------------------------------------
# fbref et pl_events ont déjà les bonnes colonnes (home_team, away_team, date)
# On renomme pour fdcu :
fdcu = fdcu.rename(columns={'HomeTeam': 'home_team', 'AwayTeam': 'away_team', 'Date': 'date'})


# ---------------------------------------------------------
# ÉTAPE 2 : Créer les dictionnaires de correction
# Objectif : Tout calquer sur le format de 'pl_events'
# ---------------------------------------------------------

# Dictionnaire pour corriger fbref
map_fbref = {
    'Manchester Utd': 'Manchester United',
    'Brighton': 'Brighton & Hove Albion',
    'Wolves': 'Wolverhampton'
}

# Dictionnaire pour corriger fdcu
map_fdcu = {
    'Man United': 'Manchester United',
    'Ipswich': 'Ipswich Town',
    "Nott'm Forest": 'Nottingham Forest',
    'Newcastle': 'Newcastle United',
    'West Ham': 'West Ham United',
    'Leicester': 'Leicester City',
    'Brighton': 'Brighton & Hove Albion',
    'Man City': 'Manchester City',
    'Tottenham': 'Tottenham Hotspur',
    'Wolves': 'Wolverhampton',
    'Leeds': 'Leeds United'
}


# ---------------------------------------------------------
# ÉTAPE 3 : Fonction de nettoyage universelle
# ---------------------------------------------------------
def clean_and_map(df, mapping_dict=None):
    df_clean = df.copy()
    
    # Appliquer le dictionnaire si fourni
    if mapping_dict:
        df_clean['home_team'] = df_clean['home_team'].replace(mapping_dict)
        df_clean['away_team'] = df_clean['away_team'].replace(mapping_dict)
    
    # Retirer les espaces invisibles avant/après
    df_clean['home_team'] = df_clean['home_team'].str.strip()
    df_clean['away_team'] = df_clean['away_team'].str.strip()
    
    # Convertir en datetime et forcer l'heure à minuit pour éviter les erreurs de format
    df_clean['date'] = pd.to_datetime(df_clean['date']).dt.normalize()
    
    return df_clean

# Application du nettoyage aux 3 DataFrames
pl_events_clean = clean_and_map(pl_events, mapping_dict=None) # Déjà le bon standard
fbref_clean     = clean_and_map(fbref, mapping_dict=map_fbref)
fdcu_clean      = clean_and_map(fdcu, mapping_dict=map_fdcu)


# ---------------------------------------------------------
# ÉTAPE 4 : Fusionner (Merge) les 3 DataFrames
# ---------------------------------------------------------

# 1. Fusion pl_events + fbref
merged_1 = pd.merge(
    pl_events_clean, 
    fbref_clean, 
    on=['home_team', 'away_team', 'date'], 
    how='inner',
    suffixes=('', '_fbref') # Gère les colonnes en double (ex: 'referee' présent dans les deux)
)

# 2. Fusion (pl_events + fbref) + fdcu
final_df = pd.merge(
    merged_1, 
    fdcu_clean, 
    on=['home_team', 'away_team', 'date'], 
    how='inner',
    suffixes=('', '_fdcu') # Gère les colonnes en double
)

# ---------------------------------------------------------
# VÉRIFICATION
# ---------------------------------------------------------
print(f"Lignes dans pl_events : {len(pl_events)}")
print(f"Lignes dans fbref     : {len(fbref)}")
print(f"Lignes dans fdcu      : {len(fdcu)}")
print("-" * 30)
print(f"Lignes après fusion   : {len(final_df)}")

Lignes dans pl_events : 719
Lignes dans fbref     : 760
Lignes dans fdcu      : 718
------------------------------
Lignes après fusion   : 675

In [237]:
# 1. Chercher ce qui bloque avec fbref
test_fbref = pd.merge(pl_events_clean, fbref_clean, on=['home_team', 'away_team', 'date'], how='left', indicator=True)
erreurs_fbref = test_fbref[test_fbref['_merge'] == 'left_only'][['home_team', 'away_team', 'date']]

print(f"Matchs perdus à cause de fbref : {len(erreurs_fbref)}")
if len(erreurs_fbref) > 0:
    print(erreurs_fbref.head(10))

print("\n" + "="*40 + "\n")

# 2. Chercher ce qui bloque avec fdcu
test_fdcu = pd.merge(pl_events_clean, fdcu_clean, on=['home_team', 'away_team', 'date'], how='left', indicator=True)
erreurs_fdcu = test_fdcu[test_fdcu['_merge'] == 'left_only'][['home_team', 'away_team', 'date']]

print(f"Matchs perdus à cause de fdcu : {len(erreurs_fdcu)}")
if len(erreurs_fdcu) > 0:
    print(erreurs_fdcu.head(10))

Matchs perdus à cause de fbref : 43
             home_team          away_team       date
476          Liverpool        Aston Villa 2025-11-02
479         Sunderland            Everton 2025-11-04
484            Chelsea      Wolverhampton 2025-11-09
499  Manchester United            Everton 2025-11-25
504  Tottenham Hotspur             Fulham 2025-11-30
512   Newcastle United  Tottenham Hotspur 2025-12-03
517          Liverpool         Sunderland 2025-12-04
518       Leeds United            Chelsea 2025-12-04
519  Manchester United    West Ham United 2025-12-05
529      Wolverhampton  Manchester United 2025-12-09

========================================

Matchs perdus à cause de fdcu : 44
             home_team          away_team       date
476          Liverpool        Aston Villa 2025-11-02
479         Sunderland            Everton 2025-11-04
484            Chelsea      Wolverhampton 2025-11-09
499  Manchester United            Everton 2025-11-25
504  Tottenham Hotspur             Fulham 2025-11-30
512   Newcastle United  Tottenham Hotspur 2025-12-03
517          Liverpool         Sunderland 2025-12-04
518       Leeds United            Chelsea 2025-12-04
519  Manchester United    West Ham United 2025-12-05
529      Wolverhampton  Manchester United 2025-12-09