In [1]:
import pandas as pd
import numpy as np
import json

In [2]:
clubelo = pd.read_csv("data/clubelo.csv")
fbref2024 = pd.read_csv("data/fbref_games2024.csv")
fbref2025 = pd.read_csv("data/fbref_games2025.csv")
fbref_team2024 = pd.read_csv("data/fbref_team_season_stats2024.csv")
fbref_team2025 = pd.read_csv("data/fbref_team_season_stats2025.csv")
meteo = pd.read_csv("data/historique_meteo.csv")
managers = pd.read_csv("data/managers.csv")
pl_events = pd.read_csv("data/pl_events.csv")
fdcu2024 = pd.read_csv("data/pl_fdcu24_25.csv")
fdcu2025 = pd.read_csv("data/pl_fdcu25_26.csv")
referees = pd.read_csv("data/referees.csv")

## Fbref

In [3]:
fbref = pd.concat([fbref2024, fbref2025], ignore_index=True)

In [4]:
fbref.columns.tolist()

['week',
 'day',
 'date',
 'time',
 'home_team',
 'score',
 'away_team',
 'attendance',
 'venue',
 'referee',
 'match_report',
 'notes',
 'game_id']

In [5]:
fbref = fbref[["home_team", "away_team", "attendance", "referee", "venue", "game_id", "date"]]

In [6]:
print(fbref.shape)
fbref.head()

(760, 7)

,home_team,away_team,attendance,referee,venue,game_id,date
0,Manchester Utd,Fulham,73297.0,Robert Jones,Old Trafford,cc5b4244,2024-08-16
1,Arsenal,Wolves,60261.0,Jarred Gillett,Emirates Stadium,c0e3342a,2024-08-17
2,Everton,Brighton,39217.0,Simon Hooper,Goodison Park,71618ace,2024-08-17
3,Ipswich Town,Liverpool,30014.0,Tim Robinson,Portman Road Stadium,a1d0d529,2024-08-17
4,Newcastle United,Southampton,52196.0,Craig Pawson,St James' Park,34557647,2024-08-17

## Football Data UK

In [7]:
fdcu = pd.concat([fdcu2024, fdcu2025], ignore_index=True)

In [8]:
fdcu2024.columns.tolist()

['Div',
 'Date',
 'Time',
 'HomeTeam',
 'AwayTeam',
 'FTHG',
 'FTAG',
 'FTR',
 'HTHG',
 'HTAG',
 'HTR',
 'Referee',
 'HS',
 'AS',
 'HST',
 'AST',
 'HF',
 'AF',
 'HC',
 'AC',
 'HY',
 'AY',
 'HR',
 'AR',
 'B365H',
 'B365D',
 'B365A',
 'BWH',
 'BWD',
 'BWA',
 'BFH',
 'BFD',
 'BFA',
 'PSH',
 'PSD',
 'PSA',
 'WHH',
 'WHD',
 'WHA',
 '1XBH',
 '1XBD',
 '1XBA',
 'MaxH',
 'MaxD',
 'MaxA',
 'AvgH',
 'AvgD',
 'AvgA',
 'BFEH',
 'BFED',
 'BFEA',
 'B365>2.5',
 'B365<2.5',
 'P>2.5',
 'P<2.5',
 'Max>2.5',
 'Max<2.5',
 'Avg>2.5',
 'Avg<2.5',
 'BFE>2.5',
 'BFE<2.5',
 'AHh',
 'B365AHH',
 'B365AHA',
 'PAHH',
 'PAHA',
 'MaxAHH',
 'MaxAHA',
 'AvgAHH',
 'AvgAHA',
 'BFEAHH',
 'BFEAHA',
 'B365CH',
 'B365CD',
 'B365CA',
 'BWCH',
 'BWCD',
 'BWCA',
 'BFCH',
 'BFCD',
 'BFCA',
 'PSCH',
 'PSCD',
 'PSCA',
 'WHCH',
 'WHCD',
 'WHCA',
 '1XBCH',
 '1XBCD',
 '1XBCA',
 'MaxCH',
 'MaxCD',
 'MaxCA',
 'AvgCH',
 'AvgCD',
 'AvgCA',
 'BFECH',
 'BFECD',
 'BFECA',
 'B365C>2.5',
 'B365C<2.5',
 'PC>2.5',
 'PC<2.5',
 'MaxC>2.5',
 'MaxC<2.5',
 'AvgC>2.5',
 'AvgC<2.5',
 'BFEC>2.5',
 'BFEC<2.5',
 'AHCh',
 'B365CAHH',
 'B365CAHA',
 'PCAHH',
 'PCAHA',
 'MaxCAHH',
 'MaxCAHA',
 'AvgCAHH',
 'AvgCAHA',
 'BFECAHH',
 'BFECAHA']

In [9]:
fdcu = fdcu.drop(columns=['Div', 'Time'])

In [10]:
fdcu.head()

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,...,BMGMCA,BVCH,BVCD,BVCA,CLCH,CLCD,CLCA,LBCH,LBCD,LBCA
0,16/08/2024,Man United,Fulham,1,0,H,0,0,D,R Jones,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,17/08/2024,Ipswich,Liverpool,0,2,A,0,0,D,T Robinson,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,17/08/2024,Arsenal,Wolves,2,0,H,1,0,H,J Gillett,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,17/08/2024,Everton,Brighton,0,3,A,0,1,A,S Hooper,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,17/08/2024,Newcastle,Southampton,1,0,H,1,0,H,C Pawson,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
fdcu = fdcu[[col for col in fdcu.columns if not col.startswith(('B365', 'BW', 'BF', 'WH', '1XB'))]]

In [12]:
print(fdcu.shape)
fdcu.head()

(718, 90)

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,...,BMGMCA,BVCH,BVCD,BVCA,CLCH,CLCD,CLCA,LBCH,LBCD,LBCA
0,16/08/2024,Man United,Fulham,1,0,H,0,0,D,R Jones,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,17/08/2024,Ipswich,Liverpool,0,2,A,0,0,D,T Robinson,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,17/08/2024,Arsenal,Wolves,2,0,H,1,0,H,J Gillett,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,17/08/2024,Everton,Brighton,0,3,A,0,1,A,S Hooper,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,17/08/2024,Newcastle,Southampton,1,0,H,1,0,H,C Pawson,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
fdcu['Date'] = pd.to_datetime(fdcu['Date'], format='%d/%m/%Y')
fdcu['Date'] = fdcu['Date'].dt.strftime('%Y-%m-%d')

In [14]:
fdcu.head()

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,...,BMGMCA,BVCH,BVCD,BVCA,CLCH,CLCD,CLCA,LBCH,LBCD,LBCA
0,2024-08-16,Man United,Fulham,1,0,H,0,0,D,R Jones,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-08-17,Ipswich,Liverpool,0,2,A,0,0,D,T Robinson,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-08-17,Arsenal,Wolves,2,0,H,1,0,H,J Gillett,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-08-17,Everton,Brighton,0,3,A,0,1,A,S Hooper,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-08-17,Newcastle,Southampton,1,0,H,1,0,H,C Pawson,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## BSD

In [15]:
pl_events.columns.tolist()

['id',
 'home_team',
 'away_team',
 'event_date',
 'round_number',
 'group_name',
 'status',
 'home_score',
 'away_score',
 'home_score_ht',
 'away_score_ht',
 'current_minute',
 'period',
 'odds_home',
 'odds_draw',
 'odds_away',
 'odds_over_15',
 'odds_over_25',
 'odds_over_35',
 'odds_under_15',
 'odds_under_25',
 'odds_under_35',
 'odds_btts_yes',
 'odds_btts_no',
 'actual_home_xg',
 'actual_away_xg',
 'home_xg_live',
 'away_xg_live',
 'penalty_shootout',
 'unavailable_players',
 'incidents',
 'live_stats',
 'lineups',
 'shotmap',
 'momentum',
 'xg_per_minute',
 'average_positions',
 'ai_preview',
 'league_id',
 'league_name',
 'league_slug',
 'season_id',
 'season_name',
 'season_year',
 'home_team_obj_id',
 'home_team_obj_name',
 'home_team_obj_short_name',
 'away_team_obj_id',
 'away_team_obj_name',
 'away_team_obj_short_name',
 'home_coach_id',
 'home_coach_name',
 'away_coach_id',
 'away_coach_name',
 'referee_id',
 'referee_name',
 'venue_id',
 'venue_name',
 'venue_city',
 'venue_capacity']

In [16]:
pl_events.head()

,id,home_team,away_team,event_date,round_number,group_name,status,home_score,away_score,home_score_ht,...,home_coach_id,home_coach_name,away_coach_id,away_coach_name,referee_id,referee_name,venue_id,venue_name,venue_city,venue_capacity
0,160173,Manchester United,Fulham,2024-08-16T20:00:00+04:00,1,NaN,finished,1.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,17,Old Trafford,Manchester,74879
1,160174,Ipswich Town,Liverpool,2024-08-17T12:30:00+04:00,1,NaN,finished,0.0,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,195,Portman Road Stadium,Ipswich,29673
2,160178,Nottingham Forest,Bournemouth,2024-08-17T15:00:00+04:00,1,NaN,finished,1.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,15,City Ground,Nottingham,30445
3,160175,Arsenal,Bolton Wanderers,2024-08-17T15:00:00+04:00,1,NaN,finished,2.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,18,Emirates Stadium,London,60704
4,160176,Everton,Brighton & Hove Albion,2024-08-17T15:00:00+04:00,1,NaN,finished,0.0,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,20,Hill Dickinson Stadium,Liverpool,52888

In [17]:
pl_events = pl_events[pl_events["status"] == "finished"]

In [18]:
pl_events.head()

,id,home_team,away_team,event_date,round_number,group_name,status,home_score,away_score,home_score_ht,...,home_coach_id,home_coach_name,away_coach_id,away_coach_name,referee_id,referee_name,venue_id,venue_name,venue_city,venue_capacity
0,160173,Manchester United,Fulham,2024-08-16T20:00:00+04:00,1,NaN,finished,1.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,17,Old Trafford,Manchester,74879
1,160174,Ipswich Town,Liverpool,2024-08-17T12:30:00+04:00,1,NaN,finished,0.0,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,195,Portman Road Stadium,Ipswich,29673
2,160178,Nottingham Forest,Bournemouth,2024-08-17T15:00:00+04:00,1,NaN,finished,1.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,15,City Ground,Nottingham,30445
3,160175,Arsenal,Bolton Wanderers,2024-08-17T15:00:00+04:00,1,NaN,finished,2.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,18,Emirates Stadium,London,60704
4,160176,Everton,Brighton & Hove Albion,2024-08-17T15:00:00+04:00,1,NaN,finished,0.0,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,20,Hill Dickinson Stadium,Liverpool,52888

In [19]:
pl_events = pl_events[['id',
 'home_team',
 'away_team',
 'event_date',
 'home_score',
 'away_score',
 'actual_home_xg',
 'actual_away_xg',
 'home_team_obj_id',
 'away_team_obj_id',
 'home_coach_id',
 'home_coach_name',
 'away_coach_id',
 'away_coach_name',
 'referee_id',
 'referee_name',
 'venue_id',
 'venue_name',
 'venue_city',
 'season_id',
 'unavailable_players']]

In [20]:
print(pl_events.shape)
pl_events.head()

(719, 21)

,id,home_team,away_team,event_date,home_score,away_score,actual_home_xg,actual_away_xg,home_team_obj_id,away_team_obj_id,...,home_coach_name,away_coach_id,away_coach_name,referee_id,referee_name,venue_id,venue_name,venue_city,season_id,unavailable_players
0,160173,Manchester United,Fulham,2024-08-16T20:00:00+04:00,1.0,0.0,NaN,NaN,17,6,...,NaN,NaN,NaN,NaN,NaN,17,Old Trafford,Manchester,336,"{""home"": [{""name"": ""Bryan Mbeumo"", ""status"": ""..."
1,160174,Ipswich Town,Liverpool,2024-08-17T12:30:00+04:00,0.0,2.0,NaN,NaN,200,1,...,NaN,NaN,NaN,NaN,NaN,195,Portman Road Stadium,Ipswich,336,"{""home"": [{""name"": ""Ashley Young"", ""status"": ""..."
2,160178,Nottingham Forest,Bournemouth,2024-08-17T15:00:00+04:00,1.0,1.0,NaN,NaN,15,2,...,NaN,NaN,NaN,NaN,NaN,15,City Ground,Nottingham,336,"{""home"": [{""name"": ""Callum Hudson-Odoi"", ""stat..."
3,160175,Arsenal,Bolton Wanderers,2024-08-17T15:00:00+04:00,2.0,0.0,NaN,NaN,18,1247,...,NaN,NaN,NaN,NaN,NaN,18,Emirates Stadium,London,336,"{""home"": [{""name"": ""Bukayo Saka"", ""status"": ""i..."
4,160176,Everton,Brighton & Hove Albion,2024-08-17T15:00:00+04:00,0.0,3.0,NaN,NaN,20,5,...,NaN,NaN,NaN,NaN,NaN,20,Hill Dickinson Stadium,Liverpool,336,"{""home"": [{""name"": ""Beto"", ""status"": ""injured""..."

In [21]:
pl_events['event_date'] = pd.to_datetime(pl_events['event_date'])
pl_events['event_date'] = pl_events['event_date'].dt.strftime('%Y-%m-%d')

In [22]:
pl_events.head()

,id,home_team,away_team,event_date,home_score,away_score,actual_home_xg,actual_away_xg,home_team_obj_id,away_team_obj_id,...,home_coach_name,away_coach_id,away_coach_name,referee_id,referee_name,venue_id,venue_name,venue_city,season_id,unavailable_players
0,160173,Manchester United,Fulham,2024-08-16,1.0,0.0,NaN,NaN,17,6,...,NaN,NaN,NaN,NaN,NaN,17,Old Trafford,Manchester,336,"{""home"": [{""name"": ""Bryan Mbeumo"", ""status"": ""..."
1,160174,Ipswich Town,Liverpool,2024-08-17,0.0,2.0,NaN,NaN,200,1,...,NaN,NaN,NaN,NaN,NaN,195,Portman Road Stadium,Ipswich,336,"{""home"": [{""name"": ""Ashley Young"", ""status"": ""..."
2,160178,Nottingham Forest,Bournemouth,2024-08-17,1.0,1.0,NaN,NaN,15,2,...,NaN,NaN,NaN,NaN,NaN,15,City Ground,Nottingham,336,"{""home"": [{""name"": ""Callum Hudson-Odoi"", ""stat..."
3,160175,Arsenal,Bolton Wanderers,2024-08-17,2.0,0.0,NaN,NaN,18,1247,...,NaN,NaN,NaN,NaN,NaN,18,Emirates Stadium,London,336,"{""home"": [{""name"": ""Bukayo Saka"", ""status"": ""i..."
4,160176,Everton,Brighton & Hove Albion,2024-08-17,0.0,3.0,NaN,NaN,20,5,...,NaN,NaN,NaN,NaN,NaN,20,Hill Dickinson Stadium,Liverpool,336,"{""home"": [{""name"": ""Beto"", ""status"": ""injured""..."

## FBref Team Stats

In [23]:
fbref_team2024.columns.tolist()

['players_used',
 'Age',
 'Poss',
 'Playing Time',
 'Playing Time.1',
 'Playing Time.2',
 'Playing Time.3',
 'Performance',
 'Performance.1',
 'Performance.2',
 'Performance.3',
 'Performance.4',
 'Performance.5',
 'Performance.6',
 'Performance.7',
 'Per 90 Minutes',
 'Per 90 Minutes.1',
 'Per 90 Minutes.2',
 'Per 90 Minutes.3',
 'Per 90 Minutes.4',
 'url']

In [24]:
fbref_team2024.head()

,players_used,Age,Poss,Playing Time,Playing Time.1,Playing Time.2,Playing Time.3,Performance,Performance.1,Performance.2,...,Performance.4,Performance.5,Performance.6,Performance.7,Per 90 Minutes,Per 90 Minutes.1,Per 90 Minutes.2,Per 90 Minutes.3,Per 90 Minutes.4,url
0,NaN,NaN,NaN,MP,Starts,Min,90s,Gls,Ast,G+A,...,PK,PKatt,CrdY,CrdR,Gls,Ast,G+A,G-PK,G+A-PK,NaN
1,25.0,25.8,56.9,38,418,3420,38,67,55,122,...,2,2,70,6,1.76,1.45,3.21,1.71,3.16,/en/squads/18bb7c10/2024-2025/Arsenal-Stats
2,28.0,27.0,50.5,38,418,3420,38,56,45,101,...,3,6,76,4,1.47,1.18,2.66,1.39,2.58,/en/squads/8602292d/2024-2025/Aston-Villa-Stats
3,29.0,25.1,48.5,38,418,3420,38,57,41,98,...,6,7,97,3,1.5,1.08,2.58,1.34,2.42,/en/squads/4ba7cbea/2024-2025/Bournemouth-Stats
4,28.0,25.8,47.9,38,418,3420,38,65,44,109,...,5,6,62,1,1.71,1.16,2.87,1.58,2.74,/en/squads/cd051869/2024-2025/Brentford-Stats

In [25]:
def process_fbref_team_data(df):
    """
    Pipeline complète : Renommage, Extraction du club, Sélection et 
    Normalisation des statistiques (division par 38).
    """
    
    # 1. Renommage des colonnes (Fusion des deux niveaux d'en-tête)
    nouveaux_noms = []
    for nom_colonne, sous_categorie in zip(df.columns, df.iloc[0]):
        # On retire le suffixe .1, .2 ajouté par pandas
        nom_principal = nom_colonne.split('.')[0] 
        
        if pd.isna(sous_categorie):
            nouveaux_noms.append(nom_principal)
        else:
            nouveaux_noms.append(f"{nom_principal}_{sous_categorie}")
            
    df.columns = nouveaux_noms

    # 2. Suppression de la ligne 0 (sous-catégories) et reset de l'index
    df = df.iloc[1:].reset_index(drop=True)

    # 3. Extraction du nom du club depuis la colonne 'url'
    # Logique : on prend la partie après le dernier '/', puis on retire '-Stats'
    if 'url' in df.columns:
        df['club'] = df['url'].str.split('/').str[-1].str.replace('-Stats', '', regex=False)

    # 4. Sélection des colonnes cibles
    # Note : On inclut 'club' dans la sélection
    colonnes_a_garder = [
        "club", "players_used", "Age", "Poss", 
        "Per 90 Minutes_Gls", "Per 90 Minutes_Ast", 
        "Performance_PK", "Performance_PKatt", 
        "Performance_CrdY", "Performance_CrdR"
    ]
    
    # On filtre en vérifiant que les colonnes existent bien
    df = df[[c for c in colonnes_a_garder if c in df.columns]].copy()

    # 5. Conversion en numérique et division par 38
    # On cible les PK et les Cartons (CrdY et CrdR)
    cols_a_transformer = [
        'Performance_PK', 'Performance_PKatt', 
        'Performance_CrdY', 'Performance_CrdR'
    ]
    
    for col in cols_a_transformer:
        if col in df.columns:
            # On force la conversion en nombre avant de diviser
            df[col] = pd.to_numeric(df[col], errors='coerce') / 38
            
    return df

# --- Utilisation ---
fbref_team2024 = process_fbref_team_data(fbref_team2024)
fbref_team2025 = process_fbref_team_data(fbref_team2025)
fbref_team2024["season"] = "2024-2025"
fbref_team2025["season"] = "2025-2026"

In [26]:
fbref_team = pd.concat([fbref_team2024, fbref_team2025], ignore_index = True)

In [27]:
fbref_team.head()

,club,players_used,Age,Poss,Per 90 Minutes_Gls,Per 90 Minutes_Ast,Performance_PK,Performance_PKatt,Performance_CrdY,Performance_CrdR,season
0,Arsenal,25.0,25.8,56.9,1.76,1.45,0.052632,0.052632,1.842105,0.157895,2024-2025
1,Aston-Villa,28.0,27.0,50.5,1.47,1.18,0.078947,0.157895,2.000000,0.105263,2024-2025
2,Bournemouth,29.0,25.1,48.5,1.5,1.08,0.157895,0.184211,2.552632,0.078947,2024-2025
3,Brentford,28.0,25.8,47.9,1.71,1.16,0.131579,0.157895,1.631579,0.026316,2024-2025
4,Brighton-and-Hove-Albion,32.0,24.8,52.3,1.68,1.08,0.184211,0.184211,2.052632,0.078947,2024-2025

## Clubelo

In [28]:
clubelo.head()

   Rank     Club Country  Level          Elo        From          To
0   4.0  Arsenal     ENG      1  1949.485474  2024-08-18  2024-08-22
1   4.0  Arsenal     ENG      1  1949.749512  2024-08-23  2024-08-24
2   4.0  Arsenal     ENG      1  1956.878906  2024-08-25  2024-08-29
3   3.0  Arsenal     ENG      1  1956.935181  2024-08-30  2024-08-30
4   4.0  Arsenal     ENG      1  1956.935181  2024-08-31  2024-08-31

In [29]:
clubelo.columns.tolist()

['Rank', 'Club', 'Country', 'Level', 'Elo', 'From', 'To']

In [30]:
clubelo = clubelo[["Club", "Elo", "From", "To"]]

In [31]:
clubelo.head()

      Club          Elo        From          To
0  Arsenal  1949.485474  2024-08-18  2024-08-22
1  Arsenal  1949.749512  2024-08-23  2024-08-24
2  Arsenal  1956.878906  2024-08-25  2024-08-29
3  Arsenal  1956.935181  2024-08-30  2024-08-30
4  Arsenal  1956.935181  2024-08-31  2024-08-31

## Météo

In [32]:
meteo.head()

,Home_Team,Away_Team,Date,Temp_Moy_C,Humidite_Moy_%,Pluie_Tot_mm,Neige_Tot_cm,Vent_Moy_kmh,Rafale_Max_kmh
0,Manchester Utd,Fulham,2024-08-16,14.3,75.0,0.0,0.0,5.1,15.8
1,Arsenal,Wolves,2024-08-17,21.9,41.7,0.0,0.0,8.0,20.5
2,Everton,Brighton,2024-08-17,17.4,62.7,0.0,0.0,11.9,26.6
3,Ipswich Town,Liverpool,2024-08-17,22.2,48.0,0.0,0.0,7.2,20.5
4,Newcastle United,Southampton,2024-08-17,18.7,56.7,0.0,0.0,18.4,34.6

In [33]:
meteo = meteo.rename(columns={"Home_Team" : "home_team", "Away_Team": "away_team", "Date" : "date"})

In [34]:
meteo.head()

,home_team,away_team,date,Temp_Moy_C,Humidite_Moy_%,Pluie_Tot_mm,Neige_Tot_cm,Vent_Moy_kmh,Rafale_Max_kmh
0,Manchester Utd,Fulham,2024-08-16,14.3,75.0,0.0,0.0,5.1,15.8
1,Arsenal,Wolves,2024-08-17,21.9,41.7,0.0,0.0,8.0,20.5
2,Everton,Brighton,2024-08-17,17.4,62.7,0.0,0.0,11.9,26.6
3,Ipswich Town,Liverpool,2024-08-17,22.2,48.0,0.0,0.0,7.2,20.5
4,Newcastle United,Southampton,2024-08-17,18.7,56.7,0.0,0.0,18.4,34.6

## Managers

In [35]:
managers.head()

,id,name,short_name,country,preferred_formation,formations_used,profile,team_style,pressing_intensity,defensive_line,...,avg_fouls,clean_sheet_pct,btts_pct,over_25_pct,over_15_pct,fail_to_score_pct,avg_goals_scored_1h,avg_goals_conceded_1h,current_team_id,current_team_name
0,662,Abdeslam Ouaddou,A. Ouaddou,Morocco,NaN,{},attacking,soft,NaN,NaN,...,NaN,75.0,0.0,100.0,100.0,25.0,0.50,0.25,608,Orlando Pirates
1,28,Abdu Maikaba,A. Maikaba,Nigeria,4-3-3,"{'4-3-3': 33, '4-2-1-3': 1}",defensive,soft,NaN,NaN,...,NaN,31.4,40.0,28.6,57.1,40.0,0.52,0.57,579,Wikki Tourists FC
2,162,Abel Ferreira,A. Ferreira,Portugal,4-2-3-1,"{'3-4-3': 1, '4-4-2': 8, '3-1-4-2': 1, '3-4-2-...",attacking,neutral,0.584073,high,...,14.12,37.7,54.7,56.6,69.8,17.0,1.18,0.35,162,Palmeiras
3,945,Abraham Paz,A. Paz,Spain,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1493,Antequera
4,1254,Adam Lakeland,A. Lakeland,England,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1889,FC Halifax Town

In [36]:
managers.columns.tolist()

['id',
 'name',
 'short_name',
 'country',
 'preferred_formation',
 'formations_used',
 'profile',
 'team_style',
 'pressing_intensity',
 'defensive_line',
 'tactical_styles',
 'matches_total',
 'wins',
 'draws',
 'losses',
 'win_pct',
 'avg_goals_scored',
 'avg_goals_conceded',
 'avg_possession',
 'avg_shots',
 'avg_shots_on_target',
 'avg_xg_for',
 'avg_xg_against',
 'avg_corners',
 'avg_yellow_cards',
 'avg_red_cards',
 'avg_fouls',
 'clean_sheet_pct',
 'btts_pct',
 'over_25_pct',
 'over_15_pct',
 'fail_to_score_pct',
 'avg_goals_scored_1h',
 'avg_goals_conceded_1h',
 'current_team_id',
 'current_team_name']

In [37]:
managers = managers.drop(columns=["short_name", "formations_used", "tactical_styles", "matches_total", "over_25_pct", "over_15_pct", "fail_to_score_pct",  'avg_goals_scored_1h', 'avg_goals_conceded_1h'])

In [38]:
managers.head()

,id,name,country,preferred_formation,profile,team_style,pressing_intensity,defensive_line,wins,draws,...,avg_xg_for,avg_xg_against,avg_corners,avg_yellow_cards,avg_red_cards,avg_fouls,clean_sheet_pct,btts_pct,current_team_id,current_team_name
0,662,Abdeslam Ouaddou,Morocco,NaN,attacking,soft,NaN,NaN,3,0,...,NaN,NaN,NaN,0.00,0.25,NaN,75.0,0.0,608,Orlando Pirates
1,28,Abdu Maikaba,Nigeria,4-3-3,defensive,soft,NaN,NaN,9,13,...,NaN,NaN,3.60,1.10,0.05,NaN,31.4,40.0,579,Wikki Tourists FC
2,162,Abel Ferreira,Portugal,4-2-3-1,attacking,neutral,0.584073,high,34,10,...,1.42,0.92,6.08,1.94,0.12,14.12,37.7,54.7,162,Palmeiras
3,945,Abraham Paz,Spain,NaN,NaN,NaN,NaN,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1493,Antequera
4,1254,Adam Lakeland,England,NaN,NaN,NaN,NaN,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1889,FC Halifax Town

## Referees

In [39]:
referees.head()

,name,country,matches,avg_yellow_per_match,avg_red_per_match,avg_goals_per_match,avg_fouls_per_match,total_yellow_cards,total_red_cards,career_games,career_yellow_cards,career_red_cards
0,Damaso Arcediano Monescillo,Spain,45,5.29,0.13,2.47,28.7,238,6,NaN,1797.0,40.0
1,Jon Ander Gonzalez Esteban,Spain,44,4.45,0.25,2.70,24.6,196,11,NaN,707.0,39.0
2,Manuel Angel Perez Hernandez,Spain,43,5.79,0.12,2.67,27.0,249,5,NaN,268.0,5.0
3,Davi de Oliveira Lacerda,Brazil,42,1.57,0.07,2.52,23.0,66,3,NaN,383.0,8.0
4,Carlos Muniz Munoz,Spain,42,3.67,0.14,2.52,26.7,154,6,NaN,166.0,8.0

In [40]:
referees = referees.drop(columns=["country", "matches", "total_yellow_cards", "total_red_cards", "career_games", "career_yellow_cards", "career_red_cards"])

In [41]:
referees.head()

,name,avg_yellow_per_match,avg_red_per_match,avg_goals_per_match,avg_fouls_per_match
0,Damaso Arcediano Monescillo,5.29,0.13,2.47,28.7
1,Jon Ander Gonzalez Esteban,4.45,0.25,2.70,24.6
2,Manuel Angel Perez Hernandez,5.79,0.12,2.67,27.0
3,Davi de Oliveira Lacerda,1.57,0.07,2.52,23.0
4,Carlos Muniz Munoz,3.67,0.14,2.52,26.7

In [42]:
referees.describe()

,avg_yellow_per_match,avg_red_per_match,avg_goals_per_match,avg_fouls_per_match
count,970.000000,970.000000,970.000000,675.000000
mean,2.814433,0.100887,2.728691,24.413481
std,1.833760,0.210440,1.054703,4.015446
min,0.000000,0.000000,0.000000,7.000000
25%,1.710000,0.000000,2.112500,22.000000
50%,2.500000,0.000000,2.735000,24.100000
75%,3.800000,0.120000,3.177500,26.600000
max,12.000000,2.000000,9.000000,41.000000

## Merge all stats

In [43]:
fbref.head()

,home_team,away_team,attendance,referee,venue,game_id,date
0,Manchester Utd,Fulham,73297.0,Robert Jones,Old Trafford,cc5b4244,2024-08-16
1,Arsenal,Wolves,60261.0,Jarred Gillett,Emirates Stadium,c0e3342a,2024-08-17
2,Everton,Brighton,39217.0,Simon Hooper,Goodison Park,71618ace,2024-08-17
3,Ipswich Town,Liverpool,30014.0,Tim Robinson,Portman Road Stadium,a1d0d529,2024-08-17
4,Newcastle United,Southampton,52196.0,Craig Pawson,St James' Park,34557647,2024-08-17

In [44]:
fbref["home_team"].unique()

<ArrowStringArray>
[   'Manchester Utd',           'Arsenal',           'Everton',
      'Ipswich Town',  'Newcastle United', 'Nottingham Forest',
   'West Ham United',         'Brentford',           'Chelsea',
    'Leicester City',       'Aston Villa',          'Brighton',
    'Crystal Palace',            'Fulham',   'Manchester City',
       'Southampton', 'Tottenham Hotspur',       'Bournemouth',
         'Liverpool',            'Wolves',        'Sunderland',
      'Leeds United',           'Burnley']
Length: 23, dtype: str

In [45]:
pl_events.head()

,id,home_team,away_team,event_date,home_score,away_score,actual_home_xg,actual_away_xg,home_team_obj_id,away_team_obj_id,...,home_coach_name,away_coach_id,away_coach_name,referee_id,referee_name,venue_id,venue_name,venue_city,season_id,unavailable_players
0,160173,Manchester United,Fulham,2024-08-16,1.0,0.0,NaN,NaN,17,6,...,NaN,NaN,NaN,NaN,NaN,17,Old Trafford,Manchester,336,"{""home"": [{""name"": ""Bryan Mbeumo"", ""status"": ""..."
1,160174,Ipswich Town,Liverpool,2024-08-17,0.0,2.0,NaN,NaN,200,1,...,NaN,NaN,NaN,NaN,NaN,195,Portman Road Stadium,Ipswich,336,"{""home"": [{""name"": ""Ashley Young"", ""status"": ""..."
2,160178,Nottingham Forest,Bournemouth,2024-08-17,1.0,1.0,NaN,NaN,15,2,...,NaN,NaN,NaN,NaN,NaN,15,City Ground,Nottingham,336,"{""home"": [{""name"": ""Callum Hudson-Odoi"", ""stat..."
3,160175,Arsenal,Bolton Wanderers,2024-08-17,2.0,0.0,NaN,NaN,18,1247,...,NaN,NaN,NaN,NaN,NaN,18,Emirates Stadium,London,336,"{""home"": [{""name"": ""Bukayo Saka"", ""status"": ""i..."
4,160176,Everton,Brighton & Hove Albion,2024-08-17,0.0,3.0,NaN,NaN,20,5,...,NaN,NaN,NaN,NaN,NaN,20,Hill Dickinson Stadium,Liverpool,336,"{""home"": [{""name"": ""Beto"", ""status"": ""injured""..."

In [46]:
pl_events["home_team"].unique()

<ArrowStringArray>
[     'Manchester United',           'Ipswich Town',      'Nottingham Forest',
                'Arsenal',                'Everton',       'Newcastle United',
        'West Ham United',              'Brentford',                'Chelsea',
         'Leicester City', 'Brighton & Hove Albion',      'Tottenham Hotspur',
        'Manchester City',         'Crystal Palace',            'Southampton',
                 'Fulham',            'Aston Villa',            'Bournemouth',
       'Bolton Wanderers',              'Liverpool',             'Sunderland',
          'Wolverhampton',           'Leeds United',                'Burnley']
Length: 24, dtype: str

In [47]:
fdcu.head()

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,...,BMGMCA,BVCH,BVCD,BVCA,CLCH,CLCD,CLCA,LBCH,LBCD,LBCA
0,2024-08-16,Man United,Fulham,1,0,H,0,0,D,R Jones,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-08-17,Ipswich,Liverpool,0,2,A,0,0,D,T Robinson,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-08-17,Arsenal,Wolves,2,0,H,1,0,H,J Gillett,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-08-17,Everton,Brighton,0,3,A,0,1,A,S Hooper,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-08-17,Newcastle,Southampton,1,0,H,1,0,H,C Pawson,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
fdcu["HomeTeam"].unique()

<ArrowStringArray>
[    'Man United',        'Ipswich',        'Arsenal',        'Everton',
      'Newcastle',  'Nott'm Forest',       'West Ham',      'Brentford',
        'Chelsea',      'Leicester',       'Brighton', 'Crystal Palace',
         'Fulham',       'Man City',    'Southampton',      'Tottenham',
    'Aston Villa',    'Bournemouth',         'Wolves',      'Liverpool',
     'Sunderland',          'Leeds',        'Burnley']
Length: 23, dtype: str

In [49]:
# ---------------------------------------------------------
# ÉTAPE 0 : Correction des anomalies dans la source pl_events
# ---------------------------------------------------------
pl_events['home_team'] = pl_events['home_team'].replace({'Bolton Wanderers': 'Wolverhampton'})
pl_events['away_team'] = pl_events['away_team'].replace({'Bolton Wanderers': 'Wolverhampton'})

# ---------------------------------------------------------
# ÉTAPE 1 : Uniformiser les colonnes de jointure
# ---------------------------------------------------------
fdcu = fdcu.rename(columns={'HomeTeam': 'home_team', 'AwayTeam': 'away_team', 'Date': 'date'})
pl_events = pl_events.rename(columns={'event_date' : 'date'})

# ---------------------------------------------------------
# ÉTAPE 2 : Créer les dictionnaires de correction
# ---------------------------------------------------------
map_fbref = {
    'Manchester Utd': 'Manchester United',
    'Brighton': 'Brighton & Hove Albion',
    'Wolves': 'Wolverhampton'
}

map_fdcu = {
    'Man United': 'Manchester United',
    'Ipswich': 'Ipswich Town',
    "Nott'm Forest": 'Nottingham Forest',
    'Newcastle': 'Newcastle United',
    'West Ham': 'West Ham United',
    'Leicester': 'Leicester City',
    'Brighton': 'Brighton & Hove Albion',
    'Man City': 'Manchester City',
    'Tottenham': 'Tottenham Hotspur',
    'Wolves': 'Wolverhampton',
    'Leeds': 'Leeds United'
}

# ---------------------------------------------------------
# ÉTAPE 3 : Fonction de nettoyage universelle
# ---------------------------------------------------------
def clean_and_map(df, mapping_dict=None):
    df_clean = df.copy()
    
    if mapping_dict:
        df_clean['home_team'] = df_clean['home_team'].replace(mapping_dict)
        df_clean['away_team'] = df_clean['away_team'].replace(mapping_dict)
    
    df_clean['home_team'] = df_clean['home_team'].str.strip()
    df_clean['away_team'] = df_clean['away_team'].str.strip()
    df_clean['date'] = pd.to_datetime(df_clean['date']).dt.normalize()
    
    return df_clean

# Application du nettoyage
pl_events_clean = clean_and_map(pl_events, mapping_dict=None)
fbref_clean     = clean_and_map(fbref, mapping_dict=map_fbref)
fdcu_clean      = clean_and_map(fdcu, mapping_dict=map_fdcu)

# ---------------------------------------------------------
# ÉTAPE 4 : Fusion avec tolérance (+/- 1 jour) et priorité FDCU
# ---------------------------------------------------------
# 1. Fusion pl_events + fbref 
merged_1 = pd.merge(
    pl_events_clean, 
    fbref_clean, 
    on=['home_team', 'away_team'], 
    how='inner',
    suffixes=('', '_fbref')
)
merged_1 = merged_1[(merged_1['date'] - merged_1['date_fbref']).abs() <= pd.Timedelta(days=1)]
merged_1 = merged_1.drop(columns=['date_fbref']) 

# 2. Fusion (pl_events + fbref) + fdcu
final_df = pd.merge(
    merged_1, 
    fdcu_clean, 
    on=['home_team', 'away_team'], 
    how='inner', 
    suffixes=('', '_fdcu')
)
final_df = final_df[(final_df['date'] - final_df['date_fdcu']).abs() <= pd.Timedelta(days=1)]

# 3. CONSERVATION DE LA DATE FDCU
final_df['date'] = final_df['date_fdcu']
final_df = final_df.drop(columns=['date_fdcu'])

# ---------------------------------------------------------
# VÉRIFICATION GLOBALE
# ---------------------------------------------------------
print(f"Lignes dans pl_events : {len(pl_events_clean)}")
print(f"Lignes dans fbref     : {len(fbref_clean)}")
print(f"Lignes dans fdcu      : {len(fdcu_clean)}")
print("-" * 30)
print(f"Lignes après fusion   : {len(final_df)}")

Lignes dans pl_events : 719
Lignes dans fbref     : 760
Lignes dans fdcu      : 718
------------------------------
Lignes après fusion   : 718

In [50]:
final_df.head()

,id,home_team,away_team,date,home_score,away_score,actual_home_xg,actual_away_xg,home_team_obj_id,away_team_obj_id,...,BMGMCA,BVCH,BVCD,BVCA,CLCH,CLCD,CLCA,LBCH,LBCD,LBCA
0,160173,Manchester United,Fulham,2024-08-16,1.0,0.0,NaN,NaN,17,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,160174,Ipswich Town,Liverpool,2024-08-17,0.0,2.0,NaN,NaN,200,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,160178,Nottingham Forest,Bournemouth,2024-08-17,1.0,1.0,NaN,NaN,15,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,160175,Arsenal,Wolverhampton,2024-08-17,2.0,0.0,NaN,NaN,18,1247,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,160176,Everton,Brighton & Hove Albion,2024-08-17,0.0,3.0,NaN,NaN,20,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [51]:
fbref_team.head()

,club,players_used,Age,Poss,Per 90 Minutes_Gls,Per 90 Minutes_Ast,Performance_PK,Performance_PKatt,Performance_CrdY,Performance_CrdR,season
0,Arsenal,25.0,25.8,56.9,1.76,1.45,0.052632,0.052632,1.842105,0.157895,2024-2025
1,Aston-Villa,28.0,27.0,50.5,1.47,1.18,0.078947,0.157895,2.000000,0.105263,2024-2025
2,Bournemouth,29.0,25.1,48.5,1.5,1.08,0.157895,0.184211,2.552632,0.078947,2024-2025
3,Brentford,28.0,25.8,47.9,1.71,1.16,0.131579,0.157895,1.631579,0.026316,2024-2025
4,Brighton-and-Hove-Albion,32.0,24.8,52.3,1.68,1.08,0.184211,0.184211,2.052632,0.078947,2024-2025

In [52]:
fbref_team['season'] = np.where(fbref_team['season'] == '2024-2025', 336, 337)

In [53]:
fbref_team.head()

,club,players_used,Age,Poss,Per 90 Minutes_Gls,Per 90 Minutes_Ast,Performance_PK,Performance_PKatt,Performance_CrdY,Performance_CrdR,season
0,Arsenal,25.0,25.8,56.9,1.76,1.45,0.052632,0.052632,1.842105,0.157895,336
1,Aston-Villa,28.0,27.0,50.5,1.47,1.18,0.078947,0.157895,2.000000,0.105263,336
2,Bournemouth,29.0,25.1,48.5,1.5,1.08,0.157895,0.184211,2.552632,0.078947,336
3,Brentford,28.0,25.8,47.9,1.71,1.16,0.131579,0.157895,1.631579,0.026316,336
4,Brighton-and-Hove-Albion,32.0,24.8,52.3,1.68,1.08,0.184211,0.184211,2.052632,0.078947,336

In [54]:
fbref_team = fbref_team.rename(columns={"season":"season_id"})

In [55]:
fbref_team.head()

,club,players_used,Age,Poss,Per 90 Minutes_Gls,Per 90 Minutes_Ast,Performance_PK,Performance_PKatt,Performance_CrdY,Performance_CrdR,season_id
0,Arsenal,25.0,25.8,56.9,1.76,1.45,0.052632,0.052632,1.842105,0.157895,336
1,Aston-Villa,28.0,27.0,50.5,1.47,1.18,0.078947,0.157895,2.000000,0.105263,336
2,Bournemouth,29.0,25.1,48.5,1.5,1.08,0.157895,0.184211,2.552632,0.078947,336
3,Brentford,28.0,25.8,47.9,1.71,1.16,0.131579,0.157895,1.631579,0.026316,336
4,Brighton-and-Hove-Albion,32.0,24.8,52.3,1.68,1.08,0.184211,0.184211,2.052632,0.078947,336

In [56]:
final_df.columns.tolist()

['id',
 'home_team',
 'away_team',
 'date',
 'home_score',
 'away_score',
 'actual_home_xg',
 'actual_away_xg',
 'home_team_obj_id',
 'away_team_obj_id',
 'home_coach_id',
 'home_coach_name',
 'away_coach_id',
 'away_coach_name',
 'referee_id',
 'referee_name',
 'venue_id',
 'venue_name',
 'venue_city',
 'season_id',
 'unavailable_players',
 'attendance',
 'referee',
 'venue',
 'game_id',
 'FTHG',
 'FTAG',
 'FTR',
 'HTHG',
 'HTAG',
 'HTR',
 'Referee',
 'HS',
 'AS',
 'HST',
 'AST',
 'HF',
 'AF',
 'HC',
 'AC',
 'HY',
 'AY',
 'HR',
 'AR',
 'PSH',
 'PSD',
 'PSA',
 'MaxH',
 'MaxD',
 'MaxA',
 'AvgH',
 'AvgD',
 'AvgA',
 'P>2.5',
 'P<2.5',
 'Max>2.5',
 'Max<2.5',
 'Avg>2.5',
 'Avg<2.5',
 'AHh',
 'PAHH',
 'PAHA',
 'MaxAHH',
 'MaxAHA',
 'AvgAHH',
 'AvgAHA',
 'PSCH',
 'PSCD',
 'PSCA',
 'MaxCH',
 'MaxCD',
 'MaxCA',
 'AvgCH',
 'AvgCD',
 'AvgCA',
 'PC>2.5',
 'PC<2.5',
 'MaxC>2.5',
 'MaxC<2.5',
 'AvgC>2.5',
 'AvgC<2.5',
 'AHCh',
 'PCAHH',
 'PCAHA',
 'MaxCAHH',
 'MaxCAHA',
 'AvgCAHH',
 'AvgCAHA',
 'BMGMH',
 'BMGMD',
 'BMGMA',
 'BVH',
 'BVD',
 'BVA',
 'CLH',
 'CLD',
 'CLA',
 'LBH',
 'LBD',
 'LBA',
 'BMGMCH',
 'BMGMCD',
 'BMGMCA',
 'BVCH',
 'BVCD',
 'BVCA',
 'CLCH',
 'CLCD',
 'CLCA',
 'LBCH',
 'LBCD',
 'LBCA']

In [57]:
final_df.head()

,id,home_team,away_team,date,home_score,away_score,actual_home_xg,actual_away_xg,home_team_obj_id,away_team_obj_id,...,BMGMCA,BVCH,BVCD,BVCA,CLCH,CLCD,CLCA,LBCH,LBCD,LBCA
0,160173,Manchester United,Fulham,2024-08-16,1.0,0.0,NaN,NaN,17,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,160174,Ipswich Town,Liverpool,2024-08-17,0.0,2.0,NaN,NaN,200,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,160178,Nottingham Forest,Bournemouth,2024-08-17,1.0,1.0,NaN,NaN,15,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,160175,Arsenal,Wolverhampton,2024-08-17,2.0,0.0,NaN,NaN,18,1247,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,160176,Everton,Brighton & Hove Albion,2024-08-17,0.0,3.0,NaN,NaN,20,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [58]:
fbref_team['club'].unique()

array(['Arsenal', 'Aston-Villa', 'Bournemouth', 'Brentford',
       'Brighton-and-Hove-Albion', 'Chelsea', 'Crystal-Palace', 'Everton',
       'Fulham', 'Ipswich-Town', 'Leicester-City', 'Liverpool',
       'Manchester-City', 'Manchester-United', 'Newcastle-United',
       'Nottingham-Forest', 'Southampton', 'Tottenham-Hotspur',
       'West-Ham-United', 'Wolverhampton-Wanderers', 'Burnley',
       'Leeds-United', 'Sunderland'], dtype=object)

In [59]:
final_df['home_team'].unique()

<ArrowStringArray>
[     'Manchester United',           'Ipswich Town',      'Nottingham Forest',
                'Arsenal',                'Everton',       'Newcastle United',
        'West Ham United',              'Brentford',                'Chelsea',
         'Leicester City', 'Brighton & Hove Albion',      'Tottenham Hotspur',
        'Manchester City',         'Crystal Palace',            'Southampton',
                 'Fulham',            'Aston Villa',            'Bournemouth',
          'Wolverhampton',              'Liverpool',             'Sunderland',
           'Leeds United',                'Burnley']
Length: 23, dtype: str

In [60]:
# 1. Création d'un dictionnaire de correspondance spécifique pour FBRef
# On gère les cas particuliers (tirets, "&", suffixes "Wanderers", etc.)
mapping_fbref_clubs = {
    'Brighton-and-Hove-Albion': 'Brighton & Hove Albion',
    'Wolverhampton-Wanderers': 'Wolverhampton',
    'Aston-Villa': 'Aston Villa',
    'Crystal-Palace': 'Crystal Palace',
    'Ipswich-Town': 'Ipswich Town',
    'Leicester-City': 'Leicester City',
    'Manchester-City': 'Manchester City',
    'Manchester-United': 'Manchester United',
    'Newcastle-United': 'Newcastle United',
    'Nottingham-Forest': 'Nottingham Forest',
    'Tottenham-Hotspur': 'Tottenham Hotspur',
    'West-Ham-United': 'West Ham United',
    'Leeds-United': 'Leeds United',
    'Bournemouth': 'Bournemouth',
    'Southampton': 'Southampton'
}

# Fonction pour normaliser les noms fbref_team['club']
def normalize_fbref_team_name(name):
    # Si le nom est dans notre dico d'exceptions
    if name in mapping_fbref_clubs:
        return mapping_fbref_clubs[name]
    # Sinon, on remplace simplement les tirets par des espaces
    return name.replace('-', ' ')

# Appliquer la normalisation sur le dataset des équipes
fbref_team['club_clean'] = fbref_team['club'].apply(normalize_fbref_team_name)

# 2. Identification des colonnes de statistiques à ramener
# On exclut les clés de jointure ('club', 'club_clean', 'season_id')
stats_cols = [c for c in fbref_team.columns if c not in ['club', 'club_clean', 'season_id']]

# ---------------------------------------------------------
# 3. FUSION POUR L'ÉQUIPE DOMICILE (HOME)
# ---------------------------------------------------------
final_df = pd.merge(
    final_df,
    fbref_team,
    left_on=['home_team', 'season_id'],
    right_on=['club_clean', 'season_id'],
    how='left'
)

# Renommer les colonnes ajoutées avec le préfixe 'home_'
final_df = final_df.rename(columns={c: f'home_{c}' for c in stats_cols})
# Supprimer les colonnes de jointure inutiles après merge
final_df = final_df.drop(columns=['club', 'club_clean'])

# ---------------------------------------------------------
# 4. FUSION POUR L'ÉQUIPE EXTÉRIEURE (AWAY)
# ---------------------------------------------------------
final_df = pd.merge(
    final_df,
    fbref_team,
    left_on=['away_team', 'season_id'],
    right_on=['club_clean', 'season_id'],
    how='left'
)

# Renommer les colonnes ajoutées avec le préfixe 'away_'
final_df = final_df.rename(columns={c: f'away_{c}' for c in stats_cols})
# Supprimer les colonnes de jointure inutiles après merge
final_df = final_df.drop(columns=['club', 'club_clean'])

print(f"Fusion terminée !  {len(final_df.shape)}")

Fusion terminée !  2

In [61]:
final_df.shape

(718, 130)

In [62]:
clubelo.head()

      Club          Elo        From          To
0  Arsenal  1949.485474  2024-08-18  2024-08-22
1  Arsenal  1949.749512  2024-08-23  2024-08-24
2  Arsenal  1956.878906  2024-08-25  2024-08-29
3  Arsenal  1956.935181  2024-08-30  2024-08-30
4  Arsenal  1956.935181  2024-08-31  2024-08-31

In [63]:
clubelo["Club"].unique()

<ArrowStringArray>
[         'Arsenal',         'Man City',        'Liverpool',
      'Aston Villa',       'Man United',         'Brighton',
      'Bournemouth',          'Chelsea',        'Brentford',
        'Newcastle',           'Forest',          'Everton',
           'Fulham',   'Crystal Palace',            'Leeds',
         'West Ham',        'Tottenham',       'Sunderland',
           'Wolves',          'Burnley',         'Coventry',
          'Ipswich',      'Southampton',         'Millwall',
    'Middlesbrough',          'Norwich',            'Derby',
 'Sheffield United',          'Swansea',          'Wrexham',
             'Hull',        'West Brom',       'Birmingham',
        'Blackburn',       'Portsmouth',     'Bristol City',
        'Leicester',              'QPR',          'Preston',
           'Oxford',          'Watford',            'Stoke',
         'Charlton',   'Sheffield Weds']
Length: 44, dtype: str

In [64]:
# ---------------------------------------------------------
# ÉTAPE 1 : Nettoyage et harmonisation du DataFrame Elo
# ---------------------------------------------------------

# Dictionnaire pour convertir les noms Elo vers les standards de final_df
map_elo = {
    'Man City': 'Manchester City',
    'Man United': 'Manchester United',
    'Brighton': 'Brighton & Hove Albion',
    'Newcastle': 'Newcastle United',
    'Forest': 'Nottingham Forest',
    'Tottenham': 'Tottenham Hotspur',
    'Wolves': 'Wolverhampton',
    'Ipswich': 'Ipswich Town',
    'Leeds': 'Leeds United',
    'West Ham': 'West Ham United',
    'Leicester': 'Leicester City',
    'Southampton': 'Southampton'
    # Ajoute d'autres correspondances si tu croises d'autres anomalies
}

# Appliquer le nom propre
clubelo['Club_clean'] = clubelo['Club'].replace(map_elo)

# S'assurer que les dates sont bien au format datetime pour la comparaison
clubelo['From'] = pd.to_datetime(clubelo['From']).dt.normalize()
clubelo['To'] = pd.to_datetime(clubelo['To']).dt.normalize()
final_df['date'] = pd.to_datetime(final_df['date']).dt.normalize()


# ---------------------------------------------------------
# ÉTAPE 2 : Fonction de recherche (Lookup) par inégalité
# ---------------------------------------------------------
def get_elo_for_match(team_name, match_date):
    # 1. On filtre le dataframe Elo pour ne garder que l'équipe demandée
    team_elo = clubelo[clubelo['Club_clean'] == team_name]
    
    # 2. On cherche la ligne où la date du match est comprise entre From et To
    mask = (team_elo['From'] <= match_date) & (team_elo['To'] >= match_date)
    result = team_elo[mask]
    
    # 3. Si on trouve une correspondance, on renvoie le score Elo, sinon NaN
    if not result.empty:
        return result['Elo'].iloc[0]
    else:
        return None # Aucun Elo trouvé pour cette date


# ---------------------------------------------------------
# ÉTAPE 3 : Application sur final_df (Home et Away)
# ---------------------------------------------------------

# Appliquer la fonction pour l'équipe à domicile (axis=1 permet d'envoyer la ligne entière)
final_df['home_elo'] = final_df.apply(
    lambda row: get_elo_for_match(row['home_team'], row['date']), 
    axis=1
)

# Appliquer la fonction pour l'équipe à l'extérieur
final_df['away_elo'] = final_df.apply(
    lambda row: get_elo_for_match(row['away_team'], row['date']), 
    axis=1
)

# Vérification rapide des valeurs manquantes
print("Matchs sans Elo Domicile :", final_df['home_elo'].isna().sum())
print("Matchs sans Elo Extérieur :", final_df['away_elo'].isna().sum())

Matchs sans Elo Domicile : 7
Matchs sans Elo Extérieur : 5

In [65]:
# Créer un masque pour les valeurs manquantes (Domicile OU Extérieur)
mask_missing_elo = final_df['home_elo'].isna() | final_df['away_elo'].isna()

# Filtrer le dataframe
matchs_sans_elo = final_df[mask_missing_elo]

# Sélectionner uniquement les colonnes pertinentes pour y voir clair
colonnes_diagnostic = ['date', 'home_team', 'away_team', 'home_elo', 'away_elo']

print(f"Total de matchs avec un problème d'Elo : {len(matchs_sans_elo)}")
print("-" * 50)
matchs_sans_elo[colonnes_diagnostic]

Total de matchs avec un problème d'Elo : 8
--------------------------------------------------

,date,home_team,away_team,home_elo,away_elo
0,2024-08-16,Manchester United,Fulham,NaN,1716.276367
1,2024-08-17,Ipswich Town,Liverpool,NaN,NaN
2,2024-08-17,Nottingham Forest,Bournemouth,1647.714966,NaN
3,2024-08-17,Arsenal,Wolverhampton,NaN,1677.862305
4,2024-08-17,Everton,Brighton & Hove Albion,NaN,1713.163208
5,2024-08-17,Newcastle United,Southampton,NaN,NaN
6,2024-08-17,West Ham United,Aston Villa,NaN,NaN
8,2024-08-18,Chelsea,Manchester City,NaN,NaN

In [66]:
final_df.shape

(718, 132)

In [67]:
meteo["home_team"].unique()

<ArrowStringArray>
[   'Manchester Utd',           'Arsenal',           'Everton',
      'Ipswich Town',  'Newcastle United', 'Nottingham Forest',
   'West Ham United',         'Brentford',           'Chelsea',
    'Leicester City',       'Aston Villa',          'Brighton',
    'Crystal Palace',            'Fulham',   'Manchester City',
       'Southampton', 'Tottenham Hotspur',       'Bournemouth',
         'Liverpool',            'Wolves',        'Sunderland',
      'Leeds United',           'Burnley']
Length: 23, dtype: str

In [68]:
# ---------------------------------------------------------
# ÉTAPE 6 : Intégration du DataFrame Météo
# ---------------------------------------------------------

# 1. Dictionnaire de correction
map_meteo = {
    'Manchester Utd': 'Manchester United',
    'Brighton': 'Brighton & Hove Albion',
    'Wolves': 'Wolverhampton'
}

# 2. Nettoyage (Assure-toi que les colonnes s'appellent bien 'home_team', 'away_team' et 'date')
# Si ce n'est pas le cas, décommente la ligne ci-dessous et adapte les noms :
# meteo = meteo.rename(columns={'Home': 'home_team', 'Away': 'away_team', 'Date': 'date'})

meteo_clean = clean_and_map(meteo, mapping_dict=map_meteo)

# 3. Fusion avec tolérance de +/- 1 jour (SANS CRÉER DE NaN)
final_df = pd.merge(
    final_df, 
    meteo_clean, 
    on=['home_team', 'away_team'], 
    how='inner', 
    suffixes=('', '_meteo')
)

# 4. Filtre pour l'écart de date et nettoyage
final_df = final_df[(final_df['date'] - final_df['date_meteo']).abs() <= pd.Timedelta(days=1)]
final_df = final_df.drop(columns=['date_meteo'])

print(f"Lignes après intégration de la météo : {len(final_df)}")

Lignes après intégration de la météo : 718

In [69]:
final_df.head()

,id,home_team,away_team,date,home_score,away_score,actual_home_xg,actual_away_xg,home_team_obj_id,away_team_obj_id,...,away_Performance_CrdY,away_Performance_CrdR,home_elo,away_elo,Temp_Moy_C,Humidite_Moy_%,Pluie_Tot_mm,Neige_Tot_cm,Vent_Moy_kmh,Rafale_Max_kmh
0,160173,Manchester United,Fulham,2024-08-16,1.0,0.0,NaN,NaN,17,6,...,2.105263,0.052632,NaN,1716.276367,14.3,75.0,0.0,0.0,5.1,15.8
2,160174,Ipswich Town,Liverpool,2024-08-17,0.0,2.0,NaN,NaN,200,1,...,1.763158,0.078947,NaN,NaN,22.2,48.0,0.0,0.0,7.2,20.5
3,160178,Nottingham Forest,Bournemouth,2024-08-17,1.0,1.0,NaN,NaN,15,2,...,2.552632,0.078947,1647.714966,NaN,18.9,52.7,0.0,0.0,15.5,31.3
4,160175,Arsenal,Wolverhampton,2024-08-17,2.0,0.0,NaN,NaN,18,1247,...,2.078947,0.052632,NaN,1677.862305,21.9,41.7,0.0,0.0,8.0,20.5
6,160176,Everton,Brighton & Hove Albion,2024-08-17,0.0,3.0,NaN,NaN,20,5,...,2.052632,0.078947,NaN,1713.163208,17.4,62.7,0.0,0.0,11.9,26.6

In [70]:
managers.head()

,id,name,country,preferred_formation,profile,team_style,pressing_intensity,defensive_line,wins,draws,...,avg_xg_for,avg_xg_against,avg_corners,avg_yellow_cards,avg_red_cards,avg_fouls,clean_sheet_pct,btts_pct,current_team_id,current_team_name
0,662,Abdeslam Ouaddou,Morocco,NaN,attacking,soft,NaN,NaN,3,0,...,NaN,NaN,NaN,0.00,0.25,NaN,75.0,0.0,608,Orlando Pirates
1,28,Abdu Maikaba,Nigeria,4-3-3,defensive,soft,NaN,NaN,9,13,...,NaN,NaN,3.60,1.10,0.05,NaN,31.4,40.0,579,Wikki Tourists FC
2,162,Abel Ferreira,Portugal,4-2-3-1,attacking,neutral,0.584073,high,34,10,...,1.42,0.92,6.08,1.94,0.12,14.12,37.7,54.7,162,Palmeiras
3,945,Abraham Paz,Spain,NaN,NaN,NaN,NaN,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1493,Antequera
4,1254,Adam Lakeland,England,NaN,NaN,NaN,NaN,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1889,FC Halifax Town

In [71]:
final_df.columns.tolist()

['id',
 'home_team',
 'away_team',
 'date',
 'home_score',
 'away_score',
 'actual_home_xg',
 'actual_away_xg',
 'home_team_obj_id',
 'away_team_obj_id',
 'home_coach_id',
 'home_coach_name',
 'away_coach_id',
 'away_coach_name',
 'referee_id',
 'referee_name',
 'venue_id',
 'venue_name',
 'venue_city',
 'season_id',
 'unavailable_players',
 'attendance',
 'referee',
 'venue',
 'game_id',
 'FTHG',
 'FTAG',
 'FTR',
 'HTHG',
 'HTAG',
 'HTR',
 'Referee',
 'HS',
 'AS',
 'HST',
 'AST',
 'HF',
 'AF',
 'HC',
 'AC',
 'HY',
 'AY',
 'HR',
 'AR',
 'PSH',
 'PSD',
 'PSA',
 'MaxH',
 'MaxD',
 'MaxA',
 'AvgH',
 'AvgD',
 'AvgA',
 'P>2.5',
 'P<2.5',
 'Max>2.5',
 'Max<2.5',
 'Avg>2.5',
 'Avg<2.5',
 'AHh',
 'PAHH',
 'PAHA',
 'MaxAHH',
 'MaxAHA',
 'AvgAHH',
 'AvgAHA',
 'PSCH',
 'PSCD',
 'PSCA',
 'MaxCH',
 'MaxCD',
 'MaxCA',
 'AvgCH',
 'AvgCD',
 'AvgCA',
 'PC>2.5',
 'PC<2.5',
 'MaxC>2.5',
 'MaxC<2.5',
 'AvgC>2.5',
 'AvgC<2.5',
 'AHCh',
 'PCAHH',
 'PCAHA',
 'MaxCAHH',
 'MaxCAHA',
 'AvgCAHH',
 'AvgCAHA',
 'BMGMH',
 'BMGMD',
 'BMGMA',
 'BVH',
 'BVD',
 'BVA',
 'CLH',
 'CLD',
 'CLA',
 'LBH',
 'LBD',
 'LBA',
 'BMGMCH',
 'BMGMCD',
 'BMGMCA',
 'BVCH',
 'BVCD',
 'BVCA',
 'CLCH',
 'CLCD',
 'CLCA',
 'LBCH',
 'LBCD',
 'LBCA',
 'home_players_used',
 'home_Age',
 'home_Poss',
 'home_Per 90 Minutes_Gls',
 'home_Per 90 Minutes_Ast',
 'home_Performance_PK',
 'home_Performance_PKatt',
 'home_Performance_CrdY',
 'home_Performance_CrdR',
 'away_players_used',
 'away_Age',
 'away_Poss',
 'away_Per 90 Minutes_Gls',
 'away_Per 90 Minutes_Ast',
 'away_Performance_PK',
 'away_Performance_PKatt',
 'away_Performance_CrdY',
 'away_Performance_CrdR',
 'home_elo',
 'away_elo',
 'Temp_Moy_C',
 'Humidite_Moy_%',
 'Pluie_Tot_mm',
 'Neige_Tot_cm',
 'Vent_Moy_kmh',
 'Rafale_Max_kmh']

In [72]:
final_df["home_coach_name"].unique()

<ArrowStringArray>
[                  nan,           'Arne Slot',          'Unai Emery',
     'Fabian Hurzeler',       'Régis Le Bris',    'Roberto De Zerbi',
         'Rob Edwards',       'Vitor Pereira',     'Calum McFarlane',
     'Michael Carrick',        'Daniel Farke', 'Nuno Espírito Santo',
       'Pep Guardiola',        'Scott Parker',       'Keith Andrews',
       'Andoni Iraola',        'Mikel Arteta',      'Oliver Glasner',
         'David Moyes',         'Marco Silva',          'Eddie Howe']
Length: 21, dtype: str

In [73]:
final_df["home_team"].unique()

<ArrowStringArray>
[     'Manchester United',           'Ipswich Town',      'Nottingham Forest',
                'Arsenal',                'Everton',       'Newcastle United',
        'West Ham United',              'Brentford',                'Chelsea',
         'Leicester City', 'Brighton & Hove Albion',      'Tottenham Hotspur',
        'Manchester City',         'Crystal Palace',            'Southampton',
                 'Fulham',            'Aston Villa',            'Bournemouth',
          'Wolverhampton',              'Liverpool',             'Sunderland',
           'Leeds United',                'Burnley']
Length: 23, dtype: str

In [74]:
final_df[final_df["season_id"] == 337]["home_coach_name"].unique()

<ArrowStringArray>
[          'Arne Slot',          'Unai Emery',     'Fabian Hurzeler',
       'Régis Le Bris',    'Roberto De Zerbi',         'Rob Edwards',
       'Vitor Pereira',     'Calum McFarlane',     'Michael Carrick',
        'Daniel Farke', 'Nuno Espírito Santo',       'Pep Guardiola',
        'Scott Parker',       'Keith Andrews',       'Andoni Iraola',
        'Mikel Arteta',      'Oliver Glasner',         'David Moyes',
         'Marco Silva',          'Eddie Howe']
Length: 20, dtype: str

In [75]:
managers.head()

,id,name,country,preferred_formation,profile,team_style,pressing_intensity,defensive_line,wins,draws,...,avg_xg_for,avg_xg_against,avg_corners,avg_yellow_cards,avg_red_cards,avg_fouls,clean_sheet_pct,btts_pct,current_team_id,current_team_name
0,662,Abdeslam Ouaddou,Morocco,NaN,attacking,soft,NaN,NaN,3,0,...,NaN,NaN,NaN,0.00,0.25,NaN,75.0,0.0,608,Orlando Pirates
1,28,Abdu Maikaba,Nigeria,4-3-3,defensive,soft,NaN,NaN,9,13,...,NaN,NaN,3.60,1.10,0.05,NaN,31.4,40.0,579,Wikki Tourists FC
2,162,Abel Ferreira,Portugal,4-2-3-1,attacking,neutral,0.584073,high,34,10,...,1.42,0.92,6.08,1.94,0.12,14.12,37.7,54.7,162,Palmeiras
3,945,Abraham Paz,Spain,NaN,NaN,NaN,NaN,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1493,Antequera
4,1254,Adam Lakeland,England,NaN,NaN,NaN,NaN,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1889,FC Halifax Town

In [76]:
managers[managers["name"]==""]

Empty DataFrame
Columns: [id, name, country, preferred_formation, profile, team_style, pressing_intensity, defensive_line, wins, draws, losses, win_pct, avg_goals_scored, avg_goals_conceded, avg_possession, avg_shots, avg_shots_on_target, avg_xg_for, avg_xg_against, avg_corners, avg_yellow_cards, avg_red_cards, avg_fouls, clean_sheet_pct, btts_pct, current_team_id, current_team_name]
Index: []

[0 rows x 27 columns]

In [77]:
# 1. Ton dictionnaire
dico_coachs = {
    'Manchester United': "Michael Carrick",
    'Ipswich Town': "Kieran McKenna",
    'Nottingham Forest': "Vitor Pereira",
    'Arsenal': "Mikel Arteta",
    'Everton': "David Moyes",
    'Newcastle United': "Eddie Howe",
    'West Ham United': "Nuno Espírito Santo",
    'Brentford': "Keith Andrews",
    'Chelsea': "Calum McFarlane",
    'Leicester City': "Gary Rowett",
    'Brighton & Hove Albion': "Fabian Hurzeler",
    'Tottenham Hotspur': "Roberto De Zerbi",
    'Manchester City': "Pep Guardiola",
    'Crystal Palace': "Oliver Glasner",
    'Southampton': "Tonda Eckert",
    'Fulham': "Marco Silva",
    'Aston Villa': "Unai Emery",
    'Bournemouth': "Andoni Iraola",
    'Wolverhampton': "Rob Edwards",
    'Liverpool': "Arne Slot",
    'Sunderland': "Régis Le Bris",
    'Leeds United': "Daniel Farke",
    'Burnley': "Scott Parker"
}

# 2. On identifie les lignes correspondant à la saison 336
# (Si ta colonne s'appelle 'season' et non 'season_id', adapte simplement le nom ci-dessous)
is_season_336 = final_df['season_id'] == 336

# 3. Application pour l'équipe à domicile
final_df['home_coach_name'] = np.where(
    is_season_336, 
    final_df['home_team'].map(dico_coachs).fillna(final_df['home_coach_name']), 
    final_df['home_coach_name']
)

# 4. Application pour l'équipe à l'extérieur
final_df['away_coach_name'] = np.where(
    is_season_336, 
    final_df['away_team'].map(dico_coachs).fillna(final_df['away_coach_name']), 
    final_df['away_coach_name']
)

# Vérification rapide du nombre de valeurs manquantes restantes
print("Coachs Domicile manquants :", final_df['home_coach_name'].isna().sum())
print("Coachs Extérieur manquants :", final_df['away_coach_name'].isna().sum())

Coachs Domicile manquants : 0
Coachs Extérieur manquants : 0

In [78]:
for val in dico_coachs.values() :
    print(val)
    print(managers[managers["name"]==val])

Michael Carrick
      id             name  country preferred_formation    profile team_style  \
892  831  Michael Carrick  England             3-4-2-1  attacking    neutral
893  560  Michael Carrick  England             3-4-2-1  attacking    neutral

     pressing_intensity defensive_line  wins  draws  ...  avg_xg_for  \
892            0.576464           high    17     11  ...        1.60
893                 NaN            NaN    15     10  ...        1.64

     avg_xg_against  avg_corners  avg_yellow_cards  avg_red_cards  avg_fouls  \
892            1.26         4.74              1.79           0.08       9.56
893            1.23         4.73              1.70           0.10       9.30

     clean_sheet_pct  btts_pct  current_team_id  current_team_name
892             16.7      75.0               17  Manchester United
893             15.6      75.0               17  Manchester United

[2 rows x 27 columns]
Kieran McKenna
      id            name           country preferred_formation   profile  \
717  192  Kieran McKenna  Northern Ireland             4-2-3-1  balanced

    team_style  pressing_intensity defensive_line  wins  draws  ...  \
717    neutral              0.5088           high    23     15  ...

     avg_xg_for  avg_xg_against  avg_corners  avg_yellow_cards  avg_red_cards  \
717         1.6             1.0          5.6              2.23           0.03

     avg_fouls  clean_sheet_pct  btts_pct  current_team_id  current_team_name
717      10.91             34.0      57.4              200       Ipswich Town

[1 rows x 27 columns]
Vitor Pereira
       id           name   country preferred_formation   profile team_style  \
1322  528  Vitor Pereira  Portugal             4-2-3-1  balanced    neutral

      pressing_intensity defensive_line  wins  draws  ...  avg_xg_for  \
1322            0.423528            mid    17     13  ...        1.37

      avg_xg_against  avg_corners  avg_yellow_cards  avg_red_cards  avg_fouls  \
1322            1.24          5.5              1.52           0.06      11.65

      clean_sheet_pct  btts_pct  current_team_id  current_team_name
1322             30.0      44.0               15  Nottingham Forest

[1 rows x 27 columns]
Mikel Arteta
      id          name country preferred_formation    profile team_style  \
918  488  Mikel Arteta   Spain               4-3-3  attacking       soft

     pressing_intensity defensive_line  wins  draws  ...  avg_xg_for  \
918            0.497734            mid    39     10  ...        1.73

     avg_xg_against  avg_corners  avg_yellow_cards  avg_red_cards  avg_fouls  \
918            0.75         5.82              1.46            0.0      10.33

     clean_sheet_pct  btts_pct  current_team_id  current_team_name
918             50.0      46.4               18            Arsenal

[1 rows x 27 columns]
David Moyes
      id         name   country preferred_formation   profile team_style  \
261  551  David Moyes  Scotland             4-2-3-1  balanced    neutral

     pressing_intensity defensive_line  wins  draws  ...  avg_xg_for  \
261            0.383576           high    14      9  ...        1.19

     avg_xg_against  avg_corners  avg_yellow_cards  avg_red_cards  avg_fouls  \
261            1.41         4.21               1.6           0.08      10.24

     clean_sheet_pct  btts_pct  current_team_id  current_team_name
261             32.4      45.9               20            Everton

[1 rows x 27 columns]
Eddie Howe
      id        name  country preferred_formation   profile team_style  \
297  557  Eddie Howe  England               4-3-3  balanced    neutral

     pressing_intensity defensive_line  wins  draws  ...  avg_xg_for  \
297            0.381729            mid    22     10  ...        1.62

     avg_xg_against  avg_corners  avg_yellow_cards  avg_red_cards  avg_fouls  \
297            1.37         5.86              1.95            0.0       9.96

     clean_sheet_pct  btts_pct  current_team_id  current_team_name
297             24.1      66.7                4   Newcastle United

[1 rows x 27 columns]
Nuno Espírito Santo
      id                 name   country preferred_formation   profile  \
974  545  Nuno Espírito Santo  Portugal             4-2-3-1  balanced

    team_style  pressing_intensity defensive_line  wins  draws  ...  \
974    neutral            0.411606            mid     9     13  ...

     avg_xg_for  avg_xg_against  avg_corners  avg_yellow_cards  avg_red_cards  \
974        1.27            1.58         5.22              1.89           0.04

     avg_fouls  clean_sheet_pct  btts_pct  current_team_id  current_team_name
974      11.35             17.9      59.0                8    West Ham United

[1 rows x 27 columns]
Keith Andrews
      id           name  country preferred_formation   profile team_style  \
701  550  Keith Andrews  Ireland             4-2-3-1  balanced    neutral

     pressing_intensity defensive_line  wins  draws  ...  avg_xg_for  \
701            0.386606           high    17     11  ...        1.57

     avg_xg_against  avg_corners  avg_yellow_cards  avg_red_cards  avg_fouls  \
701            1.31         5.06              1.48           0.03      10.81

     clean_sheet_pct  btts_pct  current_team_id  current_team_name
701             31.7      48.8               16          Brentford

[1 rows x 27 columns]
Calum McFarlane
       id             name  country preferred_formation    profile team_style  \
157  1232  Calum McFarlane  England             4-2-3-1  attacking    neutral

     pressing_intensity defensive_line  wins  draws  ...  avg_xg_for  \
157            0.602325            mid    25     11  ...        1.82

     avg_xg_against  avg_corners  avg_yellow_cards  avg_red_cards  avg_fouls  \
157            1.26         6.02              2.27           0.05      10.96

     clean_sheet_pct  btts_pct  current_team_id  current_team_name
157             27.8      59.3               13            Chelsea

[1 rows x 27 columns]
Gary Rowett
      id         name  country preferred_formation   profile team_style  \
420  177  Gary Rowett  England             4-2-3-1  balanced    neutral

     pressing_intensity defensive_line  wins  draws  ...  avg_xg_for  \
420            0.578171            mid    12     18  ...        1.12

     avg_xg_against  avg_corners  avg_yellow_cards  avg_red_cards  avg_fouls  \
420            1.39         5.15              1.74           0.06      10.93

     clean_sheet_pct  btts_pct  current_team_id  current_team_name
420             12.5      72.9              221     Leicester City

[1 rows x 27 columns]
Fabian Hurzeler
      id             name  country preferred_formation   profile team_style  \
343  549  Fabian Hurzeler  Germany             4-2-3-1  balanced    neutral

     pressing_intensity defensive_line  wins  draws  ...  avg_xg_for  \
343            0.621821            mid    16     11  ...        1.45

     avg_xg_against  avg_corners  avg_yellow_cards  avg_red_cards  avg_fouls  \
343            1.28         4.71              2.33            0.0      12.26

     clean_sheet_pct  btts_pct  current_team_id       current_team_name
343             28.2      53.8                5  Brighton & Hove Albion

[1 rows x 27 columns]
Roberto De Zerbi
       id              name country preferred_formation   profile team_style  \
1115  563  Roberto De Zerbi   Italy             4-2-3-1  balanced    neutral

      pressing_intensity defensive_line  wins  draws  ...  avg_xg_for  \
1115            0.630073            mid    15     12  ...        1.22

      avg_xg_against  avg_corners  avg_yellow_cards  avg_red_cards  avg_fouls  \
1115            1.42         5.09              2.63            0.1      11.57

      clean_sheet_pct  btts_pct  current_team_id  current_team_name
1115             31.9      53.2                9  Tottenham Hotspur

[1 rows x 27 columns]
Pep Guardiola
       id           name country preferred_formation    profile team_style  \
1040  559  Pep Guardiola   Spain             4-1-4-1  attacking    neutral

      pressing_intensity defensive_line  wins  draws  ...  avg_xg_for  \
1040            0.506302           high    37      8  ...        1.84

      avg_xg_against  avg_corners  avg_yellow_cards  avg_red_cards  avg_fouls  \
1040            1.11         6.16              1.86           0.03      10.12

      clean_sheet_pct  btts_pct  current_team_id  current_team_name
1040             42.6      48.1               12    Manchester City

[1 rows x 27 columns]
Oliver Glasner
      id            name  country preferred_formation   profile team_style  \
982  556  Oliver Glasner  Austria             3-4-2-1  balanced    neutral

     pressing_intensity defensive_line  wins  draws  ...  avg_xg_for  \
982            0.469636            mid    12     12  ...        1.52

     avg_xg_against  avg_corners  avg_yellow_cards  avg_red_cards  avg_fouls  \
982            1.26          4.3              2.08           0.04      10.82

     clean_sheet_pct  btts_pct  current_team_id  current_team_name
982             35.1      54.1               14     Crystal Palace

[1 rows x 27 columns]
Tonda Eckert
       id          name  country preferred_formation    profile team_style  \
1284  191  Tonda Eckert  Germany             4-2-3-1  attacking    neutral

      pressing_intensity defensive_line  wins  draws  ...  avg_xg_for  \
1284            0.535943            mid    26     14  ...         1.6

      avg_xg_against  avg_corners  avg_yellow_cards  avg_red_cards  avg_fouls  \
1284            1.21          5.6              1.83            0.0      10.54

      clean_sheet_pct  btts_pct  current_team_id  current_team_name
1284             26.9      69.2              205        Southampton

[1 rows x 27 columns]
Marco Silva
      id         name   country preferred_formation   profile team_style  \
827  553  Marco Silva  Portugal             4-2-3-1  balanced    neutral

     pressing_intensity defensive_line  wins  draws  ...  avg_xg_for  \
827            0.454192           high    18      7  ...        1.25

     avg_xg_against  avg_corners  avg_yellow_cards  avg_red_cards  avg_fouls  \
827            1.33         5.11              1.86            0.0      10.67

     clean_sheet_pct  btts_pct  current_team_id  current_team_name
827             24.4      56.1                6             Fulham

[1 rows x 27 columns]
Unai Emery
       id        name country preferred_formation   profile team_style  \
1293  529  Unai Emery   Spain             4-2-3-1  balanced    neutral

      pressing_intensity defensive_line  wins  draws  ...  avg_xg_for  \
1293            0.453533           high    29      8  ...        1.26

      avg_xg_against  avg_corners  avg_yellow_cards  avg_red_cards  avg_fouls  \
1293             1.3         5.09              1.53           0.03      10.13

      clean_sheet_pct  btts_pct  current_team_id  current_team_name
1293             32.7      53.1                3        Aston Villa

[1 rows x 27 columns]
Andoni Iraola
     id           name country preferred_formation   profile team_style  \
72  547  Andoni Iraola   Spain             4-2-3-1  balanced    neutral

    pressing_intensity defensive_line  wins  draws  ...  avg_xg_for  \
72            0.673133            mid    11     17  ...         1.6

    avg_xg_against  avg_corners  avg_yellow_cards  avg_red_cards  avg_fouls  \
72            1.45         5.59              2.42           0.04      11.82

    clean_sheet_pct  btts_pct  current_team_id  current_team_name
72             25.0      66.7                2        Bournemouth

[1 rows x 27 columns]
Rob Edwards
       id         name country preferred_formation   profile team_style  \
1109  546  Rob Edwards   Wales               3-5-2  balanced    neutral

      pressing_intensity defensive_line  wins  draws  ...  avg_xg_for  \
1109            0.459561           high     7      8  ...        0.87

      avg_xg_against  avg_corners  avg_yellow_cards  avg_red_cards  avg_fouls  \
1109            1.55         3.08              2.29            0.0      12.94

      clean_sheet_pct  btts_pct  current_team_id  current_team_name
1109             15.0      45.0               11      Wolverhampton

[1 rows x 27 columns]
Arne Slot
      id       name      country preferred_formation    profile team_style  \
110  507  Arne Slot  Netherlands             4-2-3-1  attacking       soft

     pressing_intensity defensive_line  wins  draws  ...  avg_xg_for  \
110            0.443374            mid    28      7  ...        1.81

     avg_xg_against  avg_corners  avg_yellow_cards  avg_red_cards  avg_fouls  \
110            1.13          6.1               1.2           0.06      10.24

     clean_sheet_pct  btts_pct  current_team_id  current_team_name
110             30.8      53.8                1          Liverpool

[1 rows x 27 columns]
Régis Le Bris
       id           name country preferred_formation   profile team_style  \
1091  564  Régis Le Bris  France             4-2-3-1  balanced    neutral

      pressing_intensity defensive_line  wins  draws  ...  avg_xg_for  \
1091             0.36982            mid    13     12  ...        1.06

      avg_xg_against  avg_corners  avg_yellow_cards  avg_red_cards  avg_fouls  \
1091            1.37         3.75              2.46            0.0      10.47

      clean_sheet_pct  btts_pct  current_team_id  current_team_name
1091             28.9      44.7                7         Sunderland

[1 rows x 27 columns]
Daniel Farke
      id          name  country preferred_formation   profile team_style  \
232  561  Daniel Farke  Germany               4-3-3  balanced    neutral

     pressing_intensity defensive_line  wins  draws  ...  avg_xg_for  \
232            0.479936            low    11     16  ...         1.5

     avg_xg_against  avg_corners  avg_yellow_cards  avg_red_cards  avg_fouls  \
232            1.47         4.61              1.54            0.0      10.71

     clean_sheet_pct  btts_pct  current_team_id  current_team_name
232             20.0      60.0               19       Leeds United

[1 rows x 27 columns]
Scott Parker
       id          name  country preferred_formation   profile team_style  \
1173  548  Scott Parker  England             4-2-3-1  balanced    neutral

      pressing_intensity defensive_line  wins  draws  ...  avg_xg_for  \
1173            0.317495            mid     6      8  ...        0.89

      avg_xg_against  avg_corners  avg_yellow_cards  avg_red_cards  avg_fouls  \
1173            1.95          3.8              1.88           0.08       9.94

      clean_sheet_pct  btts_pct  current_team_id  current_team_name
1173             10.5      60.5               10            Burnley

[1 rows x 27 columns]

In [79]:
managers_unique = managers.drop_duplicates(subset=['name'], keep='last')

In [80]:
managers.columns.tolist()

['id',
 'name',
 'country',
 'preferred_formation',
 'profile',
 'team_style',
 'pressing_intensity',
 'defensive_line',
 'wins',
 'draws',
 'losses',
 'win_pct',
 'avg_goals_scored',
 'avg_goals_conceded',
 'avg_possession',
 'avg_shots',
 'avg_shots_on_target',
 'avg_xg_for',
 'avg_xg_against',
 'avg_corners',
 'avg_yellow_cards',
 'avg_red_cards',
 'avg_fouls',
 'clean_sheet_pct',
 'btts_pct',
 'current_team_id',
 'current_team_name']

In [81]:
for val in dico_coachs.values() :
    print(val)
    print(managers_unique[managers_unique["name"]==val])

Michael Carrick
      id             name  country preferred_formation    profile team_style  \
893  560  Michael Carrick  England             3-4-2-1  attacking    neutral

     pressing_intensity defensive_line  wins  draws  ...  avg_xg_for  \
893                 NaN            NaN    15     10  ...        1.64

     avg_xg_against  avg_corners  avg_yellow_cards  avg_red_cards  avg_fouls  \
893            1.23         4.73               1.7            0.1        9.3

     clean_sheet_pct  btts_pct  current_team_id  current_team_name
893             15.6      75.0               17  Manchester United

[1 rows x 27 columns]
Kieran McKenna
      id            name           country preferred_formation   profile  \
717  192  Kieran McKenna  Northern Ireland             4-2-3-1  balanced

    team_style  pressing_intensity defensive_line  wins  draws  ...  \
717    neutral              0.5088           high    23     15  ...

     avg_xg_for  avg_xg_against  avg_corners  avg_yellow_cards  avg_red_cards  \
717         1.6             1.0          5.6              2.23           0.03

     avg_fouls  clean_sheet_pct  btts_pct  current_team_id  current_team_name
717      10.91             34.0      57.4              200       Ipswich Town

[1 rows x 27 columns]
Vitor Pereira
       id           name   country preferred_formation   profile team_style  \
1322  528  Vitor Pereira  Portugal             4-2-3-1  balanced    neutral

      pressing_intensity defensive_line  wins  draws  ...  avg_xg_for  \
1322            0.423528            mid    17     13  ...        1.37

      avg_xg_against  avg_corners  avg_yellow_cards  avg_red_cards  avg_fouls  \
1322            1.24          5.5              1.52           0.06      11.65

      clean_sheet_pct  btts_pct  current_team_id  current_team_name
1322             30.0      44.0               15  Nottingham Forest

[1 rows x 27 columns]
Mikel Arteta
      id          name country preferred_formation    profile team_style  \
918  488  Mikel Arteta   Spain               4-3-3  attacking       soft

     pressing_intensity defensive_line  wins  draws  ...  avg_xg_for  \
918            0.497734            mid    39     10  ...        1.73

     avg_xg_against  avg_corners  avg_yellow_cards  avg_red_cards  avg_fouls  \
918            0.75         5.82              1.46            0.0      10.33

     clean_sheet_pct  btts_pct  current_team_id  current_team_name
918             50.0      46.4               18            Arsenal

[1 rows x 27 columns]
David Moyes
      id         name   country preferred_formation   profile team_style  \
261  551  David Moyes  Scotland             4-2-3-1  balanced    neutral

     pressing_intensity defensive_line  wins  draws  ...  avg_xg_for  \
261            0.383576           high    14      9  ...        1.19

     avg_xg_against  avg_corners  avg_yellow_cards  avg_red_cards  avg_fouls  \
261            1.41         4.21               1.6           0.08      10.24

     clean_sheet_pct  btts_pct  current_team_id  current_team_name
261             32.4      45.9               20            Everton

[1 rows x 27 columns]
Eddie Howe
      id        name  country preferred_formation   profile team_style  \
297  557  Eddie Howe  England               4-3-3  balanced    neutral

     pressing_intensity defensive_line  wins  draws  ...  avg_xg_for  \
297            0.381729            mid    22     10  ...        1.62

     avg_xg_against  avg_corners  avg_yellow_cards  avg_red_cards  avg_fouls  \
297            1.37         5.86              1.95            0.0       9.96

     clean_sheet_pct  btts_pct  current_team_id  current_team_name
297             24.1      66.7                4   Newcastle United

[1 rows x 27 columns]
Nuno Espírito Santo
      id                 name   country preferred_formation   profile  \
974  545  Nuno Espírito Santo  Portugal             4-2-3-1  balanced

    team_style  pressing_intensity defensive_line  wins  draws  ...  \
974    neutral            0.411606            mid     9     13  ...

     avg_xg_for  avg_xg_against  avg_corners  avg_yellow_cards  avg_red_cards  \
974        1.27            1.58         5.22              1.89           0.04

     avg_fouls  clean_sheet_pct  btts_pct  current_team_id  current_team_name
974      11.35             17.9      59.0                8    West Ham United

[1 rows x 27 columns]
Keith Andrews
      id           name  country preferred_formation   profile team_style  \
701  550  Keith Andrews  Ireland             4-2-3-1  balanced    neutral

     pressing_intensity defensive_line  wins  draws  ...  avg_xg_for  \
701            0.386606           high    17     11  ...        1.57

     avg_xg_against  avg_corners  avg_yellow_cards  avg_red_cards  avg_fouls  \
701            1.31         5.06              1.48           0.03      10.81

     clean_sheet_pct  btts_pct  current_team_id  current_team_name
701             31.7      48.8               16          Brentford

[1 rows x 27 columns]
Calum McFarlane
       id             name  country preferred_formation    profile team_style  \
157  1232  Calum McFarlane  England             4-2-3-1  attacking    neutral

     pressing_intensity defensive_line  wins  draws  ...  avg_xg_for  \
157            0.602325            mid    25     11  ...        1.82

     avg_xg_against  avg_corners  avg_yellow_cards  avg_red_cards  avg_fouls  \
157            1.26         6.02              2.27           0.05      10.96

     clean_sheet_pct  btts_pct  current_team_id  current_team_name
157             27.8      59.3               13            Chelsea

[1 rows x 27 columns]
Gary Rowett
      id         name  country preferred_formation   profile team_style  \
420  177  Gary Rowett  England             4-2-3-1  balanced    neutral

     pressing_intensity defensive_line  wins  draws  ...  avg_xg_for  \
420            0.578171            mid    12     18  ...        1.12

     avg_xg_against  avg_corners  avg_yellow_cards  avg_red_cards  avg_fouls  \
420            1.39         5.15              1.74           0.06      10.93

     clean_sheet_pct  btts_pct  current_team_id  current_team_name
420             12.5      72.9              221     Leicester City

[1 rows x 27 columns]
Fabian Hurzeler
      id             name  country preferred_formation   profile team_style  \
343  549  Fabian Hurzeler  Germany             4-2-3-1  balanced    neutral

     pressing_intensity defensive_line  wins  draws  ...  avg_xg_for  \
343            0.621821            mid    16     11  ...        1.45

     avg_xg_against  avg_corners  avg_yellow_cards  avg_red_cards  avg_fouls  \
343            1.28         4.71              2.33            0.0      12.26

     clean_sheet_pct  btts_pct  current_team_id       current_team_name
343             28.2      53.8                5  Brighton & Hove Albion

[1 rows x 27 columns]
Roberto De Zerbi
       id              name country preferred_formation   profile team_style  \
1115  563  Roberto De Zerbi   Italy             4-2-3-1  balanced    neutral

      pressing_intensity defensive_line  wins  draws  ...  avg_xg_for  \
1115            0.630073            mid    15     12  ...        1.22

      avg_xg_against  avg_corners  avg_yellow_cards  avg_red_cards  avg_fouls  \
1115            1.42         5.09              2.63            0.1      11.57

      clean_sheet_pct  btts_pct  current_team_id  current_team_name
1115             31.9      53.2                9  Tottenham Hotspur

[1 rows x 27 columns]
Pep Guardiola
       id           name country preferred_formation    profile team_style  \
1040  559  Pep Guardiola   Spain             4-1-4-1  attacking    neutral

      pressing_intensity defensive_line  wins  draws  ...  avg_xg_for  \
1040            0.506302           high    37      8  ...        1.84

      avg_xg_against  avg_corners  avg_yellow_cards  avg_red_cards  avg_fouls  \
1040            1.11         6.16              1.86           0.03      10.12

      clean_sheet_pct  btts_pct  current_team_id  current_team_name
1040             42.6      48.1               12    Manchester City

[1 rows x 27 columns]
Oliver Glasner
      id            name  country preferred_formation   profile team_style  \
982  556  Oliver Glasner  Austria             3-4-2-1  balanced    neutral

     pressing_intensity defensive_line  wins  draws  ...  avg_xg_for  \
982            0.469636            mid    12     12  ...        1.52

     avg_xg_against  avg_corners  avg_yellow_cards  avg_red_cards  avg_fouls  \
982            1.26          4.3              2.08           0.04      10.82

     clean_sheet_pct  btts_pct  current_team_id  current_team_name
982             35.1      54.1               14     Crystal Palace

[1 rows x 27 columns]
Tonda Eckert
       id          name  country preferred_formation    profile team_style  \
1284  191  Tonda Eckert  Germany             4-2-3-1  attacking    neutral

      pressing_intensity defensive_line  wins  draws  ...  avg_xg_for  \
1284            0.535943            mid    26     14  ...         1.6

      avg_xg_against  avg_corners  avg_yellow_cards  avg_red_cards  avg_fouls  \
1284            1.21          5.6              1.83            0.0      10.54

      clean_sheet_pct  btts_pct  current_team_id  current_team_name
1284             26.9      69.2              205        Southampton

[1 rows x 27 columns]
Marco Silva
      id         name   country preferred_formation   profile team_style  \
827  553  Marco Silva  Portugal             4-2-3-1  balanced    neutral

     pressing_intensity defensive_line  wins  draws  ...  avg_xg_for  \
827            0.454192           high    18      7  ...        1.25

     avg_xg_against  avg_corners  avg_yellow_cards  avg_red_cards  avg_fouls  \
827            1.33         5.11              1.86            0.0      10.67

     clean_sheet_pct  btts_pct  current_team_id  current_team_name
827             24.4      56.1                6             Fulham

[1 rows x 27 columns]
Unai Emery
       id        name country preferred_formation   profile team_style  \
1293  529  Unai Emery   Spain             4-2-3-1  balanced    neutral

      pressing_intensity defensive_line  wins  draws  ...  avg_xg_for  \
1293            0.453533           high    29      8  ...        1.26

      avg_xg_against  avg_corners  avg_yellow_cards  avg_red_cards  avg_fouls  \
1293             1.3         5.09              1.53           0.03      10.13

      clean_sheet_pct  btts_pct  current_team_id  current_team_name
1293             32.7      53.1                3        Aston Villa

[1 rows x 27 columns]
Andoni Iraola
     id           name country preferred_formation   profile team_style  \
72  547  Andoni Iraola   Spain             4-2-3-1  balanced    neutral

    pressing_intensity defensive_line  wins  draws  ...  avg_xg_for  \
72            0.673133            mid    11     17  ...         1.6

    avg_xg_against  avg_corners  avg_yellow_cards  avg_red_cards  avg_fouls  \
72            1.45         5.59              2.42           0.04      11.82

    clean_sheet_pct  btts_pct  current_team_id  current_team_name
72             25.0      66.7                2        Bournemouth

[1 rows x 27 columns]
Rob Edwards
       id         name country preferred_formation   profile team_style  \
1109  546  Rob Edwards   Wales               3-5-2  balanced    neutral

      pressing_intensity defensive_line  wins  draws  ...  avg_xg_for  \
1109            0.459561           high     7      8  ...        0.87

      avg_xg_against  avg_corners  avg_yellow_cards  avg_red_cards  avg_fouls  \
1109            1.55         3.08              2.29            0.0      12.94

      clean_sheet_pct  btts_pct  current_team_id  current_team_name
1109             15.0      45.0               11      Wolverhampton

[1 rows x 27 columns]
Arne Slot
      id       name      country preferred_formation    profile team_style  \
110  507  Arne Slot  Netherlands             4-2-3-1  attacking       soft

     pressing_intensity defensive_line  wins  draws  ...  avg_xg_for  \
110            0.443374            mid    28      7  ...        1.81

     avg_xg_against  avg_corners  avg_yellow_cards  avg_red_cards  avg_fouls  \
110            1.13          6.1               1.2           0.06      10.24

     clean_sheet_pct  btts_pct  current_team_id  current_team_name
110             30.8      53.8                1          Liverpool

[1 rows x 27 columns]
Régis Le Bris
       id           name country preferred_formation   profile team_style  \
1091  564  Régis Le Bris  France             4-2-3-1  balanced    neutral

      pressing_intensity defensive_line  wins  draws  ...  avg_xg_for  \
1091             0.36982            mid    13     12  ...        1.06

      avg_xg_against  avg_corners  avg_yellow_cards  avg_red_cards  avg_fouls  \
1091            1.37         3.75              2.46            0.0      10.47

      clean_sheet_pct  btts_pct  current_team_id  current_team_name
1091             28.9      44.7                7         Sunderland

[1 rows x 27 columns]
Daniel Farke
      id          name  country preferred_formation   profile team_style  \
232  561  Daniel Farke  Germany               4-3-3  balanced    neutral

     pressing_intensity defensive_line  wins  draws  ...  avg_xg_for  \
232            0.479936            low    11     16  ...         1.5

     avg_xg_against  avg_corners  avg_yellow_cards  avg_red_cards  avg_fouls  \
232            1.47         4.61              1.54            0.0      10.71

     clean_sheet_pct  btts_pct  current_team_id  current_team_name
232             20.0      60.0               19       Leeds United

[1 rows x 27 columns]
Scott Parker
       id          name  country preferred_formation   profile team_style  \
1173  548  Scott Parker  England             4-2-3-1  balanced    neutral

      pressing_intensity defensive_line  wins  draws  ...  avg_xg_for  \
1173            0.317495            mid     6      8  ...        0.89

      avg_xg_against  avg_corners  avg_yellow_cards  avg_red_cards  avg_fouls  \
1173            1.95          3.8              1.88           0.08       9.94

      clean_sheet_pct  btts_pct  current_team_id  current_team_name
1173             10.5      60.5               10            Burnley

[1 rows x 27 columns]

In [82]:
# Utilisation de .isin() avec les valeurs du dictionnaire
# Le '&' remplace le 'and' et les parenthèses sont obligatoires
managers_incomplets = managers[
    (managers["name"].isin(dico_coachs.values())) & 
    (managers['defensive_line'].isnull() | managers['pressing_intensity'].isnull())
]

# Récupération des noms uniques
noms_managers_incomplets = managers_incomplets['name'].unique()

print(f"Nombre de managers (de ton dictionnaire) avec des données manquantes : {len(noms_managers_incomplets)}")
print("Liste des managers concernés :")
print(noms_managers_incomplets)

Nombre de managers (de ton dictionnaire) avec des données manquantes : 1
Liste des managers concernés :
<ArrowStringArray>
['Michael Carrick']
Length: 1, dtype: str

In [83]:
managers["defensive_line"].unique()

<ArrowStringArray>
[nan, 'high', 'low', 'mid']
Length: 4, dtype: str

In [84]:
managers["pressing_intensity"].describe()

count    511.000000
mean       0.500486
std        0.165961
min        0.108899
25%        0.382367
50%        0.492523
75%        0.602011
max        1.000000
Name: pressing_intensity, dtype: float64

In [85]:
managers_unique.loc[managers_unique['name'] == 'Michael Carrick', 'defensive_line'] = "mid"
managers_unique.loc[managers_unique['name'] == 'Michael Carrick', 'pressing_intensity'] = 0.50

In [86]:
# ---------------------------------------------------------
# ÉTAPE 7 : Mapper les statistiques des managers
# ---------------------------------------------------------

# 1. Identifier les colonnes de statistiques à récupérer
# On exclut la clé de jointure 'name'
manager_stats_cols = [c for c in managers_unique.columns if c != 'name']

# ---------------------------------------------------------
# 2. FUSION POUR LE MANAGER DOMICILE (HOME)
# ---------------------------------------------------------
final_df = pd.merge(
    final_df,
    managers_unique,
    left_on='home_coach_name',
    right_on='name',
    how='left'
)

# On renomme les nouvelles colonnes avec le préfixe 'home_manager_'
final_df = final_df.rename(columns={c: f'home_manager_{c}' for c in manager_stats_cols})

# On supprime la colonne 'name' qui a servi à la jointure
final_df = final_df.drop(columns=['name'])

# ---------------------------------------------------------
# 3. FUSION POUR LE MANAGER EXTÉRIEUR (AWAY)
# ---------------------------------------------------------
final_df = pd.merge(
    final_df,
    managers_unique,
    left_on='away_coach_name',
    right_on='name',
    how='left'
)

# On renomme les nouvelles colonnes avec le préfixe 'away_manager_'
final_df = final_df.rename(columns={c: f'away_manager_{c}' for c in manager_stats_cols})

# On supprime à nouveau la colonne 'name' superflue
final_df = final_df.drop(columns=['name'])

# ---------------------------------------------------------
# VÉRIFICATION FINALE
# ---------------------------------------------------------
final_df.head()

,id_x,home_team,away_team,date,home_score,away_score,actual_home_xg,actual_away_xg,home_team_obj_id,away_team_obj_id,...,away_manager_avg_xg_for,away_manager_avg_xg_against,away_manager_avg_corners,away_manager_avg_yellow_cards,away_manager_avg_red_cards,away_manager_avg_fouls,away_manager_clean_sheet_pct,away_manager_btts_pct,away_manager_current_team_id,away_manager_current_team_name
0,160173,Manchester United,Fulham,2024-08-16,1.0,0.0,NaN,NaN,17,6,...,1.25,1.33,5.11,1.86,0.00,10.67,24.4,56.1,6,Fulham
1,160174,Ipswich Town,Liverpool,2024-08-17,0.0,2.0,NaN,NaN,200,1,...,1.81,1.13,6.10,1.20,0.06,10.24,30.8,53.8,1,Liverpool
2,160178,Nottingham Forest,Bournemouth,2024-08-17,1.0,1.0,NaN,NaN,15,2,...,1.60,1.45,5.59,2.42,0.04,11.82,25.0,66.7,2,Bournemouth
3,160175,Arsenal,Wolverhampton,2024-08-17,2.0,0.0,NaN,NaN,18,1247,...,0.87,1.55,3.08,2.29,0.00,12.94,15.0,45.0,11,Wolverhampton
4,160176,Everton,Brighton & Hove Albion,2024-08-17,0.0,3.0,NaN,NaN,20,5,...,1.45,1.28,4.71,2.33,0.00,12.26,28.2,53.8,5,Brighton & Hove Albion

In [87]:
final_df.shape

(718, 190)

In [88]:
referees.head()

,name,avg_yellow_per_match,avg_red_per_match,avg_goals_per_match,avg_fouls_per_match
0,Damaso Arcediano Monescillo,5.29,0.13,2.47,28.7
1,Jon Ander Gonzalez Esteban,4.45,0.25,2.70,24.6
2,Manuel Angel Perez Hernandez,5.79,0.12,2.67,27.0
3,Davi de Oliveira Lacerda,1.57,0.07,2.52,23.0
4,Carlos Muniz Munoz,3.67,0.14,2.52,26.7

In [89]:
final_df["Referee"].unique()

<ArrowStringArray>
[     'R Jones',   'T Robinson',     'M Oliver',    'J Gillett',
     'S Hooper',     'C Pawson', 'T Harrington',    'S Barrott',
     'A Taylor',   'C Kavanagh',  'M Salisbury',       'D Bond',
      'D Coote',    'D England',    'S Attwell',      'J Smith',
      'L Smith',     'P Bankes',     'J Brooks',    'S Allison',
     'A Madley',    'T Bramall',   'K Kavanagh',     'O Oliver',
    'A Kitchen',       'D Webb',       'T Kirk',    'M Donohue',
    'P Tierney',     'F Hallam']
Length: 30, dtype: str

In [90]:
referees["name"].tolist()

['Damaso Arcediano Monescillo',
 'Jon Ander Gonzalez Esteban',
 'Manuel Angel Perez Hernandez',
 'Davi de Oliveira Lacerda',
 'Carlos Muniz Munoz',
 'Andres Fuentes Molina',
 'Iosu Galech Apezteguia',
 'Miguel Sesma Espinosa',
 'Jose Luis Guzman Mansilla',
 'Alvaro Moreno Aragon',
 'Saul Ais Reig',
 'Eder Mallo Fernandez',
 'Daniel Palencia Caballero',
 'Sergui Claudiu Muresan',
 'Salvador Lax Franco',
 'German Cid Camacho',
 'Chris Kavanagh',
 'Manuel Jesus Orellana Cid',
 'Rafael Sanchez Lopez',
 'Michael Oliver',
 'Jose Antonio Sanchez Villalobos',
 'Marta Huerta de Aza',
 'Anthony Taylor',
 'Raphael Claus',
 'Rubiel Vazquez',
 'Serdar Gozubuyuk',
 'Rosendo Mendoza',
 'Rodrigo Jose Pereira de Lima',
 'Danny Makkelie',
 'Allen Chapman',
 'Thomas Kirk',
 'Victor Rivas',
 'Wilton Pereira Sampaio',
 'Miguel Gonzalez Diaz',
 'Jon Freemon',
 'Drew Fischer',
 'Guido Gonzales Jr',
 'Anderson Daronco',
 'Mohammed Al-Hakim',
 'Rafael Rodrigo Klein',
 'Filip Dujic',
 'Sergiy Boyko',
 'François Letexier',
 'Andrew Kitchen',
 'Matt Donohue',
 'Sven Jablonski',
 'Nick Walsh',
 'Bruno Arleu de Araujo',
 'José María Sánchez Martínez',
 'Jesus Gil Manzano',
 'Felix Zwayer',
 'Farai Hallam',
 'Josh Smith',
 'Istvan Kovacs',
 'Alejandro Hernandez',
 'Maurizio Mariani',
 'Chris Penso',
 'Tobias Stieler',
 'Ricardo De Burgos Bengoetxea',
 'Pierre-Luc Lauziere',
 'Flavio Rodrigues De Souza',
 'Thomas Bramall',
 'Lewis Smith',
 'Lucas Paulo Torezin',
 'Felipe Fernandes de Lima',
 'Davide Massa',
 'Damian Sylwestrzak',
 'David Webb',
 'Paulo Cesar Zanovelli da Silva',
 'Daniel Siebert',
 'Horatiu Fesnic',
 'Granit Maqedonci',
 'Benoît Bastien',
 'Urs Schnyder',
 'Eric Lambrechts',
 'Alexis Da Silva',
 'Clement Turpin',
 'Samuel Barrott',
 'Andy Madley',
 'Adam Herczeg',
 'Darren England',
 'Marcos de Oliveira',
 'Juan Martinez Munuera',
 'Anthony Backhouse',
 'Alex Gomes Stefano',
 'Gavin Ward',
 'Sascha Stegemann',
 'Marco Guida',
 'Fredrik Klitte',
 'Victor Wolf',
 'Lawrence Visser',
 'Glenn Nyberg',
 'Ramon Abatti Abel',
 "Lothar D'hondt",
 'Stuart Attwell',
 'Tom Nield',
 'Adam Ladeback',
 'Stephen Martin',
 'Peter Bankes',
 'Szymon Marciniak',
 'Jasper Vergoote',
 'Craig Pawson',
 'César Soto Grado',
 'Matheus Delgado Candançan',
 'Kristoffer Karlsson',
 'Paweł Raczkowski',
 'Jair Antonio Maruffo',
 'Halil Umut Meler',
 'Richard Sundell',
 'Adi Aganovic',
 'Willy Delajod',
 'Sander van der Eijk',
 'John Busby',
 'Harm Osmers',
 'Javier Alberola Rojas',
 'Oscar Johnson',
 'Marco Antonio Ortiz Nava',
 'Oliver Langford',
 "Simon Bourdeaud'hui",
 'Simone Sozza',
 'Piotr Lasyk',
 'Tori Penso',
 'Nicolas Laforge',
 'Ruddy Buquet',
 'Lucas Casagrande',
 'José Luis Munuera Montero',
 'Bram Van Driessche',
 'Nathan Verboomen',
 'Joao Pedro Pinheiro',
 'Luis Bestard Servera',
 'Jarred Gillett',
 'Marian Barbu',
 'Marcel Birsan',
 'Georgi Kabakov',
 'Allard Lindhout',
 'Savio Pereira Sampaio',
 'Luís Godinho',
 'Miguel Angel Ortiz Arias',
 'Joseph Dickerson',
 'Fotis Bazakos',
 'Alejandro Muñiz Ruiz',
 'Robert Jones',
 'Damian Kos',
 'Victor Garcia Verdura',
 'Jan Boterberg',
 'Malik Badawi',
 'Gorka Etayo Herrera',
 'Bert Verbeke',
 'Alejandro Morilla Turrion',
 'Ruebyn Ricardo',
 'Cihan Aydin',
 'Karol Arys',
 'Steven McLean',
 'John Beaton',
 'Ruben Avalos Barrera',
 'Oliver de la Fuente Ramos',
 'Alejandro Quintero Gonzalez',
 'Szabolcs Kovacs',
 'Daniele Doveri',
 'Marc Nagtegaal',
 'Ricardo Montero',
 'Guillermo Cuadra Fernandez',
 'Leigh Doughty',
 'Eric Wattellier',
 'Ali Yilmaz',
 'Alejandro Ojaos Valera',
 'Isidro Diaz de Mera Escuderos',
 'Ricardo Fierro',
 'Dean Whitestone',
 'James Linington',
 'Yasin Kol',
 'Lukasz Kuzma',
 'Lorenzo Hernandez',
 'Tomasz Kwiatkowski',
 'Adrian Cordero Vega',
 'Jeroen Manschot',
 'Michael Salisbury',
 'Ben Toner',
 'Anastasios Papapetrou',
 'César Ramos Palazuelos',
 'Jérôme Brisard',
 'Wojciech Myc',
 'Patryk Gryckiewicz',
 'Rares George Vidican',
 'Tim Robinson',
 'Benjamin Brand',
 'Florian Badstubner',
 'Jeremie Pignard',
 'Alonso De Ena Wolf',
 'David Dickinson',
 'Radu Marian Petrescu',
 'Lukas Fahndrich',
 'Sam Allison',
 'Daniel Quintero Huitrón',
 'Luca Cibelli',
 'Bartosz Frankowski',
 'Tobias Welz',
 'Andrea Colombo',
 'Elliot Bell',
 'Antonio Nobre',
 'Jaroslaw Przybyl',
 'Donald Robertson',
 'Armando Villarrea',
 'John Brooks',
 'Matthew MacDermid',
 'Daniel Schlager',
 'Sandro Schärer',
 'Florin Andrei',
 'Simon Hooper',
 'Alberto Undiano Mallenco',
 'Jannick van der Laan',
 'Victor Alfonso Caceres Hernandez',
 'Ismael Rosario Lopez Penuelas',
 'Joey Kooij',
 'Oguzhan Cakir',
 'Francisco Hernandez Maeso',
 'Lorena Del Mar',
 'Tim Ford',
 'Mateo Busquets Ferrer',
 'Luis Santander',
 'Thomas Leonard',
 'Michael Fabbri',
 'Joao Antonio Ferreira Goncalves',
 'Bastien Dechepy',
 'Paul Tierney',
 'Adnan Deniz Kayatepe',
 'Beatriz Cuesta Arribas',
 'Shukri Alhunfush',
 'Elena Pelaez Arnillas',
 'Tony Harrington',
 'Ismir Pekmic',
 'David Fernández Borbalan',
 'Johannes von Mandach',
 'Benoît Millot',
 'Mehmet Turkmen',
 'Melissa Lopez Osorio',
 'Anojen Kanagasingam',
 'Wesli De Cremer',
 'Mohammed Khled Hoish',
 'Maximiliano Quintero Hernandez',
 'Fernando Hernandez',
 'Ainara Andrea Acevedo Dudley',
 'Alexandros Tsakalidis',
 'Vicente Jassiel Reynoso Arce',
 'Marc Bollengier',
 'Matteo Marchetti',
 'Matthias Jollenbeck',
 'Alex Bos',
 'Vassilis Fotias',
 'Joakim Ostling',
 'Fernando Teixeira',
 'Dragomir Draganov',
 'Christos Vergetis',
 'Volen Chinkov',
 'Mathieu Vernice',
 'David Rafael Oliveira da Silva',
 'Jeremy Stinat',
 'Marco Di Bello',
 'Robert Hartmann',
 'Paola Cebollada Lopez',
 'Stephanie Frappart',
 'Majed Mohammed Al-Shamrani',
 'Adonai Escobedo Gonzalez',
 'Atilla Karaoglan',
 'Claudio Filipe Ruivo Pereira',
 'Guillaume Paradis',
 'Daniele Chiffi',
 'Anastasios Sidiropoulos',
 'Luca Zufferli',
 'Miguel Nogueira',
 'Nico Gianforte',
 'Sven Wolfensberger',
 'Ali Sansalan',
 'Robin Hensgens',
 'Ylenia Sanchez Miguel',
 'Kadir Saglam',
 'Andrea Fernandez Firvida',
 'Alessandro Dudic',
 'Alicia Espinosa Rios',
 'Eduardo Iturralde Gonzalez',
 'Batuhan Kolak',
 'Ozan Ergun',
 'Christian Dingert',
 'Federico La Penna',
 'Elisabet Calvo Valentin',
 'Katia García',
 'Yonatan Peinado Aguirre',
 'Maria Gloria Planes Terol',
 'Oscar Mejia Garcia',
 'Bastian Dankert',
 'Florian Exner',
 'Luca Piccolo',
 'Khaled Al Teris',
 'Sebastian Coltescu',
 'Ermanno Feliciani',
 'Radoslav Gidzhenov',
 'Gael Angoula',
 'Romain Lissorgue',
 'Lukasz Szpala',
 'César Muñiz',
 'Erik Mattsson',
 'Helder Filipe Claudio Carvalho',
 'Robert Madley',
 'Iulian Calin',
 'Fabio Jose Costa Verissimo',
 'Jesus Rafael Lopez Valle',
 'Alper Akarsu',
 'Sergio Guelho',
 'Matteo Marcenaro',
 'Sergii Demianchuk',
 'Fotios Polychronis',
 'George Catalin Roman',
 'Guillermo Pacheco Larios',
 'Marian Grebencharski',
 'Hakim Ben el Salem Hadj',
 'Martin Van den Kerkhof',
 'Duncan Nicolson',
 'Deniz Aytekin',
 'Jorge Abraham Camacho Peregrina',
 'Gustavo Correia',
 'Nikola Popov',
 'Rob Dieperink',
 'James Bell',
 'Bas Nijhuis',
 'Carlos Velasco Carballo',
 'Miguel Pérez',
 'Juan Luca Sacchi',
 'Maria Eugenia Gil Soriano',
 'Georgi Ginchev',
 'Helder Malheiro',
 'Michiel Allaerts',
 'Bert Put',
 'Abdullah Al-Kharbosh',
 'Erwin Blank',
 'Tom Reeves',
 'Kevin van Damme',
 'Viorel Nicusor Flueran',
 'Sören Storks',
 'Patrick Ittrich',
 'Angelos Evangelou',
 'Francesco Fourneau',
 'Dimitar Dimitrov',
 'Donatas Rumsas',
 'Cagdas Altay',
 'Ross Hardie',
 'Pawel Malec',
 'Calum Scott',
 'Benjamin Speedie',
 'Luca Pairetto',
 'Ryan Lee',
 'Giuseppe Collu',
 'Dennis Higler',
 'Turienzo',
 'Bruno Jose Ribeiro Pires Costa',
 'Kevin Bonacina',
 'Pedro Ramalho',
 'Athanasios Tzilos',
 'Carlos Macedo',
 'Stavros Tsimenteridis',
 'Fernando Antonio Mendes de Salles Nascimento Filho',
 'Martin Petersen',
 'Vasil Minev',
 'Hiroyuki Kimura',
 'Tess Olofsson',
 'Horia Gabriel Mladinovici',
 'Mirel Turkes',
 'Slavko Vinčić',
 'Ventsislav Mitrev',
 'Abdelatif Kherradji',
 'Tobias Reichel',
 'Georgi Dimitrov',
 'Lyuboslav Lyubomirov',
 'Mohammed Sami Taher Al Ismail',
 'Kevin Clancy',
 'Anzhony Rodrigues',
 'Spyridon Zampalas',
 'Michail Matsoukas',
 'Andrei Florin Chivulete',
 'Jose Bessa',
 'Gianluca Manganiello',
 'Rade Obrenovič',
 'Alberto Ruben Arena',
 'Carlos Delgado',
 'Massimiliano Ledda',
 'Robin Braun',
 'Karen Hernandez Andrade',
 'Robert Schröder',
 'George Catalin Gaman',
 'Abdullah Al-Owaidan',
 'Marcelo de Lima Henrique',
 'Joaquin Alberto Vizcarra Armenta',
 'Oguzhan Aksu',
 'Valentin Zhelezov',
 'Faisal Suleiman Al-Balawi',
 'Martin Velikov',
 'Edward Duckworth',
 'Fedayi San',
 'Kristiyan Kolev',
 'Rosario Abisso',
 'Ingmar Oostrom',
 'Wagner do Nascimento Magalhaes',
 'Espen Eskas',
 'Sebastian Krasny',
 'Jefferson Ferreira de Moraes',
 'Bruno Pereira Vasconcelos',
 'Vasilica Iancu',
 'Todor Nedyalkov Kirov',
 'Yigit Arslan',
 'Ioannis Papadopoulos',
 'Fabio Maresca',
 'Valerio Crezzini',
 'Marcin Szczerbowicz',
 'Miguel Andre Monteiro Fonseca',
 'Luis Carlos Mateus Filipe',
 'Martijn Vos',
 'Martin Molina Astorga',
 'Timo Gerach',
 'Nikola Dabanovic',
 'Olatz Rivera Olmedo',
 'Giovanni Ayroldi',
 'Irfan Peljto',
 'Mateusz Piszczelok',
 'Ivan Kružliak',
 'Ivan Antonio Lopez Sanchez',
 'Matthew Corlett',
 'Sebastian Gishamer',
 'Frank Willenborg',
 'Joao Vitor Gobi',
 'Raquel Suarez Gonzalez',
 'Livio Marinelli',
 'Ismail Elfath',
 'Marijan Drmic',
 'Koichiro Fukushima',
 'Marcio Torres',
 'Konstantinos Katikos',
 'Masuya Ueda',
 'Luis Alfredo Garcia Rodriguez',
 'Cristian Moldoveanu',
 'Stanimir Trenchev',
 'Fareeh Al-Jaloud',
 'Khalid Al-Ahmari',
 'Abdullah Al-Harbi',
 'Abdullah Al-Shehri',
 'Desiree Grundbacher',
 'Ali Al-Qahtani',
 'Omer Tolga Guldibi',
 'Ricardo Baixinho',
 'Lionel Tschudi',
 'Miguel Ayza',
 'Alfonso Perez Burrull',
 'Salvador Perez Villalobos',
 'Diogo Rosa',
 'Martin Markov',
 'Braulio Da Silva Machado',
 'Andre Luis Skettino Policarpo Bento',
 'Byungjin Park',
 'Ko Hyung-jin',
 'Jong-Hyeok Kim',
 'Yong-jun Shin',
 'Alexandros Katsikogiannis',
 'Elijio Arreguin',
 'Antonio Rapuano',
 'Joakim Sars',
 'Gero Piskov',
 'Ionut Coza',
 'Georgi Stoyanov',
 'Stoyan Arsov',
 'Mario Terrazas Chavez',
 'Andre Filipe Domingues Narciso',
 'Will Finnie',
 'Meletios Gioumatzidis',
 'Andrei Moroita',
 'Ahmad Al Rumaikhani',
 'Adrian Viorel Cojocaru',
 'Antonio Miguel Mateu Lahoz',
 'Carlos Clos Gómez',
 'Rafael Ramírez Domínguez',
 'Daniel Stefanski',
 'Ramy Touchan',
 'Koki Nagamine',
 'Anthony Letellier',
 'Ryo Tanimoto',
 'Dae-Yong Kim',
 'Yuzo Sutani',
 'Hayato Shimizu',
 'Min-Seok Song',
 'Jonathan Benkenstein Pinheiro',
 'Gabriel Mihuleac',
 'Abdulsamad Bakri',
 'Chris Graham',
 'Ahmed Mohammed Al-Rumaikhani',
 'Edina Alves Batista',
 'Koji Takasaki',
 'Richard Martens',
 'Rohit Saggi',
 'Mohammed Nasser Abu Shaqara',
 'Umit Ozturk',
 'Sami Ahmed Al-Jurays',
 'Abdullah Zarban',
 'Abraham de Jesus Quirarte Contreras',
 'Marco Piccinini',
 'Dimitrios Moschou',
 'Jacob Miles',
 'Zorbay Kucuk',
 'José Paradas',
 'Denislav Stalev',
 'Afro Rocha De Carvalho Filho',
 'Yuri Elino Ferreira Da Cruz',
 'Gurcan Hasova',
 'Thomas Parsons',
 'Koei Koya',
 'Davide Di Marco',
 'Piero Maza',
 'Yael Falcon Perez',
 'Akihiko Ikeuchi',
 'Michael Pavlov',
 'Marcin Kochanek',
 'Lloyd Wilson',
 'Vlad Baban',
 'Sultan Al-Harbi',
 'Sorin Dan Vadana',
 'Piotr Rzucidlo',
 'Elcin Masiyev',
 'Igor Pajač',
 'Aliyar Aghayev',
 'Andris Treimanis',
 'Srdan Jovanovic',
 'Paride Tremolada',
 'Krasen Georgiev',
 'Ignacio Iglesias Villanueva',
 'José Teixeira',
 'Manuel Enrique Mejuto Gonzalez',
 'Antonio Rubinos Perez',
 'Luis Medina Cantalejo',
 'Carlos Megía Dávila',
 'Lucas Canetto Bellote',
 'Hristiyana Guteva',
 'Gustavo Ervino Bauermann',
 'Lucas Guimarães Rechatiko Horn',
 'Resat Onur Coskunses',
 'Futoshi Nakamura',
 'Nabil Bensalah',
 'Daichi Shiino',
 'Atsushi Uemura',
 'Tomasz Marciniak',
 'Andres Matonte',
 'Derlis Lopez',
 'Juan Gabriel Benitez',
 'Andres Rojas',
 'Cristian Garay',
 'Carlos Betancur',
 'Gery Vargas',
 'Ovidiu Robu',
 'Hiroki Kasahara',
 'Balazs Berke',
 'Julian Weinberger',
 'Grant Irvine',
 'Nenad Minaković',
 'Giorgi Kruashvili',
 'Goga Kikacheishvili',
 'Panagiotis Koukoulas',
 'Georgios Kokkinos',
 'Manfredas Lukjancukas',
 'Mykola Balakin',
 'Dan McFarlane',
 'Mikael Lesage',
 'Zac Kennard-Kettle',
 'Morten Krogh',
 'Simon Mather',
 'Zulema Gonzalez Gonzalez',
 'Arda Kardesler',
 'Alejandro José Hernández Hernández',
 'Mario Melero López',
 'Marco Fritz',
 'José Luis González González',
 'Bernardino Gonzalez',
 'Julian Rodriguez Santiago',
 'Arturo Daudén Ibáñez',
 'Wim Smet',
 'Andrea Calzavara',
 'Dong Jun Lee',
 'Alexis Herrera',
 'Guillermo Enrique Guerrero Alcivar',
 'Kevin Ortega',
 'Wilmar Roldan',
 'Hernan Heras',
 'Dario Herrera',
 'Jose Cabero Rebolledo',
 'Esteban Ostojich',
 'Jesús Valenzuela',
 'Facundo Raul Tello Figueroa',
 'Augusto Bergelio Aragon Bautista',
 'Gustavo Tejera',
 'Jose Burgos',
 'Cheol-Jun Choi',
 'Robert Hennessy',
 'Enea Jorgji',
 'Sang-Hyeop Chae',
 'Tae-Hwan Seol',
 'Giuseppe Mucera',
 'Omar Abdulkadir Artan',
 'Amin Mohamed Omar',
 'Stan Teuben',
 'Erdem Mertoglu',
 'Mohammad Al-Emara',
 'Juxhin Xhaja',
 'Alex Chilowicz',
 'Ndala Ngambo',
 'Jalal Jayed',
 'Pierre Ghislain Atcho',
 'Issa Sy',
 'Beida Dahane',
 'Abongile Tom',
 'Neil Hair',
 'Ross Joyce',
 'Alan Young',
 'Matthew Russell',
 'Orel Grinfeeld',
 'Kristo Tohver',
 'Matej Jug',
 'Scott Oldham',
 'David Rock',
 'Mateusz Jenda',
 'Jesús Gil Manzano',
 'Juan Martínez Munuera',
 'Felix Brych',
 'Eduardo Prieto Iglesias',
 'Xavier Estrada Fernández',
 'Piero Giacomelli',
 'Guido Winkmann',
 'Saïd Ennjimi',
 'Frank Schneider',
 'Carmine Russo',
 'Pedro Jesús Pérez Montero',
 'Jérôme Miguelgorry',
 'Johan Hamel',
 'Antonio Damato',
 'Vicente José Lizondo Cortés',
 'Brandon Stevis',
 'Edwin Van de Graaf',
 'Razvan Neagra',
 'Hyun Jae Choi',
 'Takafumi Mikuriya',
 'Atsushi Kamimura',
 'Paulo Schleich Vollkopf',
 'Jodis Nascimento de Souza',
 'Carlos P. Benitez',
 'Carlos Ortega',
 'Jhon Alexander Ospina Londono',
 'Bryan Loayza',
 'Roberto Perez Gutierrez',
 'Fernando Andre Vejar Diaz',
 'Leandro Rey Hilfer',
 'Augusto Menendez',
 'Denis da Silva Ribeiro Serafim',
 'Yusuke Ohashi',
 'Joshua Encarnacion',
 'Woo-Sung Kim',
 'Kleber Ariel Goncalves Silva',
 'Abdel Aziz Mohamed Bouh',
 'Kyriakos Athanasiou',
 'Vitalijs Spasjonnikovs',
 'Milos Milanovic',
 'Daniel McFarlane',
 'Tamas Bognar',
 'Colin Steven',
 'Luca Massimi',
 'Raed Ali Al-Zahrani',
 'Nicolas Ramirez',
 'Iuliana Elena Demetrescu',
 'Omer Faruk Turtay',
 'Abdulsamad Ali Bakri',
 'Oleksiy Derevinskyi',
 'Kirill Levnikov',
 'Daniel Laryea',
 'Antoine Valnet',
 'Mustapha Ghorbal',
 'Martin Coy',
 'Aurelien Petit',
 'Geoffrey Kubler',
 'Alexandre Perreau Niel',
 'Paul Howard',
 'Ali Mahmood Mahmood Ismail',
 'Mohamed Maarouf Eid Mansour',
 'Abdou Abdel Mefire',
 'Peter Waweru',
 'Boubou Traore',
 'Mohamed Al Smaail',
 'Pacifique Ndabihawenimana',
 'Samuel Uwikunda',
 'Ahmad Imetehaz Heeralall',
 'Aaron Farmer',
 'James Durkin',
 'Stephen Parkinson',
 'Carl Brook',
 'Richard Eley',
 'Lee Swabey',
 'Oliver Yates',
 'Mario Perri',
 'Piotr Urban',
 'Ivano Pezzuto',
 'Sebastian Stockbridge',
 'Aaron Bannister',
 'Scott Jackson',
 'Damian Krumplewski',
 'Maciej Pelka',
 'Albert Rozycki',
 'Karol Wójcik',
 'Federico Dionisi',
 'Filip Glova',
 'Natalie Simon',
 'Piotr Szypula',
 'Mateusz Stepniak',
 'Paweł Szuta',
 'Oliver Mackey',
 'Greg Dopka',
 'Christian-Petru Ciochirca',
 'Katja Koroleva',
 'Massimiliano Irrati',
 'Paolo Silvio Mazzoleni',
 'Fredy Fautrel',
 'Gianluca Rocchi',
 'Carlos del Cerro Grande',
 'Alfonso Álvarez Izquierdo',
 'Bartolomeu Varela Teles',
 'Antony Gautier',
 'Domenico Celi',
 'Peter Sippel',
 'Günter Perl',
 'Hakim Ben El Hadj Salem',
 'Jochen Drees',
 'Puentes Leira',
 'Yoshimi Yamashita',
 'Mihail Sebastian Lastun',
 'Bruno Mota Correia',
 'Arthur Gomes Rabelo',
 'Alisson Sidnei Furtado',
 'Abdullah Bugra Taskinsoy',
 'Ivo Nigel Mendez Chavez',
 'Yender Herrera',
 'Jordi Espinoza',
 'Derlis Benitez',
 'Anthony Diaz',
 'Nikolay Popnikolov',
 'Thaillan Azevedo Gomes',
 'Leo Simao Holanda',
 'Antonio Sanchez Sanchez',
 'Jose Mendonca da Silva Junior',
 'Pierry Dias dos Santos',
 'Diego Da Costa Cidral',
 'Keylor Herrera Villalobos',
 'Iwan Arwel Griffith',
 'Daniel Elder',
 'Carly Shaw MacLaren',
 'Rustam Lutfullin',
 'Duje Strukan',
 'Dumitri Muntean',
 'Walter Lopez',
 'Shaun Evans',
 'Ian McNabb',
 'Abdulla Ali Al-Marri',
 'Lorena Del Mar Trujillano Gallardo',
 'Maguielson Lima Barbosa',
 'Mitja Stegemann',
 'Spiros Zabalas',
 'Asen Albayrak',
 'Hajrim Qovanaj',
 'Jun Shin Shin',
 'Steven Madrigal',
 'Huseyin Sanli',
 'Mario Escobar',
 'Javier Feres',
 'Fatih Tokail',
 'Maria Sole Ferrieri Caputi',
 'Yusuke Araki',
 'Iván Barton',
 'Ondrej Berka',
 'Sergey Karasev',
 'Raquel Solano Suarez',
 'Andrew Humphries',
 'Djindo Louis Houngnandande',
 'Alhadi Allaou Mahamat',
 'Mustapha Kechaf',
 'Clement Franklin Kpan',
 'Messie Jessie Oved Nkounkou',
 'Mehrez Melki',
 'Lahlou Benbraham',
 'Shamirah Nabadda',
 'Patrice Tanguy Mebiame',
 'Ahmed Taleb',
 'Pierre Legat',
 'Pierre Gaillouste',
 'Karim Abed',
 'Mickael Leleu',
 'Tifenn Leprodhomme',
 'Arnaud Baert',
 'Florent Batta',
 'Eddy Rosier',
 'Remi Landry',
 'Faouzi Benchabane',
 'Samir Zolota',
 'Benjamin Lepaysant',
 'Brendan Roffet',
 'David Roome',
 'James Oldham',
 'Charles Breakspear',
 'Jose Maria Sanchez Santos',
 'Petar Mitrev',
 'Ionela Alina Pesu',
 'Direnc Tonusluoglu',
 'Andre Luiz Skettino Policarpo Bento',
 'Ben Atkinson',
 'Ross Martin',
 'Andrew Miller',
 'Steven Copeland',
 'Martin Woods',
 'Isaac Searle',
 'William Davis',
 "Jamie O'Connor",
 'Robert Massey-Ellis',
 'Wayne Cartmel',
 'Sam Mulhall',
 'Peter Wright',
 'Declan Brown',
 'Abigail Byrne',
 'Michael Barlow',
 'Elliott Swallow',
 'Jorge Tarraga Lajara',
 'Alejandro Clemente Ortuno',
 'Daniel Miranda Bolano',
 'Alfredo Ramo Andres',
 'Marcelo Ibanez Juarez',
 'Alvaro Rodriguez Recio',
 'Felix Bickel',
 'Manuel Pozueta Rodriguez',
 'Federico Javier Saiz de Villares',
 'Manuel Garcia Gomez',
 'Nestor Holgueras Castellanos',
 'David Lopez Jimenez',
 'Guillermo Conejero Sanchez',
 'Francisco Jose Ortega Herrera',
 'Pol Arenas Mora',
 'Marc Philip Eckermann',
 'Alvaro Canovas Garcia Villarubia',
 'Patrick Schwengers',
 'Szymon Rutkowski',
 'Ruben Ruiperez Marin',
 'Alexandre Aleman Perez',
 'Luis Enrique Morona Del Campo',
 'Guillermo Cueto Amigo',
 'Tom Bauer',
 'Pawel Horozaniecki',
 'Jakob Kehlet',
 'Robert Constantin Avram',
 'Todor Vukov',
 'Murilo Ugolini Klein',
 'Rafal Szydelko',
 'Valentin Stanchev',
 'Daniele Perenzoni',
 'Niccolo Turrini',
 'Tomasz Wajda',
 'Pawel Wrzeszczynski',
 'Mateusz Mastaj',
 'Patryk Swierczek',
 'Jacek Malyszek',
 'Kajetan Kasprzyk',
 'Andrea Zanotti',
 'Piotr Pazdecki',
 'Maciej Wegrzyk',
 'Szymon Lezny',
 'Georgi Minev',
 'Giovanni Baccini',
 'Lukasz Karski',
 'Alireza Faghani',
 'Richard Hempel',
 'Assad Nouhoum',
 'Cristian Ballweg',
 'Fabienne Michel',
 'Max Burda',
 'Lars Erbst',
 'Felix Weller',
 'Robert Kampka',
 'Leonidas Exuzidis',
 'Florian Lechner',
 'Felix Prigan',
 'Eric-Dominic Weisbach',
 'Nico Fuchs',
 'Wolfgang Haslberger',
 'Patrick Alt',
 'Lukas Benen',
 'Timo Gansloweit',
 'Felix Wagner',
 'Jarno Wienefeld',
 'Michael Bacher',
 'Craig Hicks',
 'Dawid Wisniewski',
 'Blazej Syropiatko',
 'Aleksander Koziel',
 'Sylwester Rasmus',
 'Simovic Novak',
 'Chrysovalantis Theouli',
 'Patrik Kolarić',
 'Darren Drysdale',
 'Jacob A. Sundberg',
 'Eldorjan Hamiti',
 'Philip Farrugia',
 'Ante Culina',
 'Martin Matoša',
 'Henrik Nalbandyan',
 'Ivar Orri Kristjansson',
 'Mohammad Usman Aslam',
 'Alyssa Pennington',
 'Visar Kastrati',
 'Ishmael Barbara',
 'Sayat Karabaev',
 'Viktor Kopievskiy',
 'Mihaly Kapraly',
 'Ben McMaster',
 'Dalibor Cerny',
 'Bence Csonka',
 'Ladislav Szikszay',
 'Pavle Ilic',
 'Dario Bel',
 'Jacob Karlsen',
 'Daniyar Sakhi',
 'Danilo Nikolic',
 'Sandi Putros',

In [91]:
# 1. Le dictionnaire complet et corrigé
map_referees = {
    'R Jones': 'Robert Jones',
    'T Robinson': 'Tim Robinson',
    'M Oliver': 'Michael Oliver',
    'J Gillett': 'Jarred Gillett',
    'S Hooper': 'Simon Hooper',
    'C Pawson': 'Craig Pawson',
    'T Harrington': 'Tony Harrington',
    'S Barrott': 'Samuel Barrott',
    'A Taylor': 'Anthony Taylor',
    'C Kavanagh': 'Chris Kavanagh',
    'M Salisbury': 'Michael Salisbury',
    'D England': 'Darren England',
    'S Attwell': 'Stuart Attwell',
    'J Smith': 'Josh Smith',
    'L Smith': 'Lewis Smith',
    'P Bankes': 'Peter Bankes',
    'J Brooks': 'John Brooks',
    'S Allison': 'Sam Allison',
    'A Madley': 'Andy Madley',
    'T Bramall': 'Thomas Bramall',
    'A Kitchen': 'Andrew Kitchen',
    'D Webb': 'David Webb',
    'T Kirk': 'Thomas Kirk',
    'M Donohue': 'Matt Donohue',
    'P Tierney': 'Paul Tierney',
    'F Hallam': 'Farai Hallam',
    'D Bond': 'Darren Bond',          # Ajout officiel
    'D Coote': 'David Coote',         # Ajout officiel
    'K Kavanagh': 'Chris Kavanagh',   # Correction de coquille
    'O Oliver': 'Michael Oliver'      # Correction de coquille
}

# 2. Application sur ton DataFrame
# Remplace 'referee' par le nom exact de ta colonne (ex: 'Referee_fdcu' ou 'referee_fbref' si elle a été renommée lors d'un merge)
nom_colonne_arbitre = 'Referee' 

final_df[nom_colonne_arbitre] = final_df[nom_colonne_arbitre].map(map_referees).fillna(final_df[nom_colonne_arbitre])

# 3. Vérification : On affiche les 5 premiers pour valider que le remplacement a fonctionné
print("Aperçu des arbitres après nettoyage :")
final_df["Referee"].head()

Aperçu des arbitres après nettoyage :

0      Robert Jones
1      Tim Robinson
2    Michael Oliver
3    Jarred Gillett
4      Simon Hooper
Name: Referee, dtype: str

In [92]:
nouveaux_arbitres = pd.DataFrame([
    {
        'name': 'David Coote',
        'avg_yellow_per_match': 5.19,
        'avg_red_per_match': 0.19,
        'avg_fouls_per_match': 24.69,
        'avg_goals_per_match': 2.85  # Valeur par défaut (moyenne PL)
    },
    {
        'name': 'Darren Bond',
        'avg_yellow_per_match': 3.93,
        'avg_red_per_match': 0.07,
        'avg_fouls_per_match': 22.29,
        'avg_goals_per_match': 2.85  # Valeur par défaut (moyenne PL)
    }
])
referees = pd.concat([referees, nouveaux_arbitres], ignore_index=True)

In [93]:
referees.head()

,name,avg_yellow_per_match,avg_red_per_match,avg_goals_per_match,avg_fouls_per_match
0,Damaso Arcediano Monescillo,5.29,0.13,2.47,28.7
1,Jon Ander Gonzalez Esteban,4.45,0.25,2.70,24.6
2,Manuel Angel Perez Hernandez,5.79,0.12,2.67,27.0
3,Davi de Oliveira Lacerda,1.57,0.07,2.52,23.0
4,Carlos Muniz Munoz,3.67,0.14,2.52,26.7

In [94]:
# ---------------------------------------------------------
# ÉTAPE 8 : Mapping des statistiques des arbitres
# ---------------------------------------------------------

# 1. Identifier les colonnes de statistiques à récupérer
# On exclut la clé de jointure 'name'
referee_stats_cols = [c for c in referees.columns if c != 'name']

# 2. Fusion (Merge)
# final_df['Referee'] doit contenir les noms complets (ex: 'Robert Jones')
final_df = pd.merge(
    final_df,
    referees,
    left_on='Referee',   # Ta clé dans le dataframe de matchs
    right_on='name',     # Ta clé dans le dataframe referees
    how='left'           # On garde tous les matchs, même si l'arbitre manque
)

# 3. Nettoyage après fusion
# On supprime la colonne 'name' qui est maintenant en double avec 'Referee'
if 'name' in final_df.columns:
    final_df = final_df.drop(columns=['name'])

# 4. Vérification du succès
print(f"Fusion des arbitres terminée !")
print(f"Colonnes ajoutées : {referee_stats_cols}")

# Diagnostic : voir s'il y a des arbitres sans stats
mask_missing = final_df[referee_stats_cols[0]].isna()
arbitres_manquants = final_df[mask_missing]['Referee'].unique()

if len(arbitres_manquants) > 0:
    print(f"⚠️ {len(arbitres_manquants)} arbitres n'ont pas été trouvés dans la base de stats :")
    print(arbitres_manquants)
else:
    print("✅ Parfait ! Tous les arbitres ont leurs statistiques.")

Fusion des arbitres terminée !
Colonnes ajoutées : ['avg_yellow_per_match', 'avg_red_per_match', 'avg_goals_per_match', 'avg_fouls_per_match']
✅ Parfait ! Tous les arbitres ont leurs statistiques.

In [95]:
final_df.shape

(718, 194)

In [96]:
final_df.columns.tolist()

['id_x',
 'home_team',
 'away_team',
 'date',
 'home_score',
 'away_score',
 'actual_home_xg',
 'actual_away_xg',
 'home_team_obj_id',
 'away_team_obj_id',
 'home_coach_id',
 'home_coach_name',
 'away_coach_id',
 'away_coach_name',
 'referee_id',
 'referee_name',
 'venue_id',
 'venue_name',
 'venue_city',
 'season_id',
 'unavailable_players',
 'attendance',
 'referee',
 'venue',
 'game_id',
 'FTHG',
 'FTAG',
 'FTR',
 'HTHG',
 'HTAG',
 'HTR',
 'Referee',
 'HS',
 'AS',
 'HST',
 'AST',
 'HF',
 'AF',
 'HC',
 'AC',
 'HY',
 'AY',
 'HR',
 'AR',
 'PSH',
 'PSD',
 'PSA',
 'MaxH',
 'MaxD',
 'MaxA',
 'AvgH',
 'AvgD',
 'AvgA',
 'P>2.5',
 'P<2.5',
 'Max>2.5',
 'Max<2.5',
 'Avg>2.5',
 'Avg<2.5',
 'AHh',
 'PAHH',
 'PAHA',
 'MaxAHH',
 'MaxAHA',
 'AvgAHH',
 'AvgAHA',
 'PSCH',
 'PSCD',
 'PSCA',
 'MaxCH',
 'MaxCD',
 'MaxCA',
 'AvgCH',
 'AvgCD',
 'AvgCA',
 'PC>2.5',
 'PC<2.5',
 'MaxC>2.5',
 'MaxC<2.5',
 'AvgC>2.5',
 'AvgC<2.5',
 'AHCh',
 'PCAHH',
 'PCAHA',
 'MaxCAHH',
 'MaxCAHA',
 'AvgCAHH',
 'AvgCAHA',
 'BMGMH',
 'BMGMD',
 'BMGMA',
 'BVH',
 'BVD',
 'BVA',
 'CLH',
 'CLD',
 'CLA',
 'LBH',
 'LBD',
 'LBA',
 'BMGMCH',
 'BMGMCD',
 'BMGMCA',
 'BVCH',
 'BVCD',
 'BVCA',
 'CLCH',
 'CLCD',
 'CLCA',
 'LBCH',
 'LBCD',
 'LBCA',
 'home_players_used',
 'home_Age',
 'home_Poss',
 'home_Per 90 Minutes_Gls',
 'home_Per 90 Minutes_Ast',
 'home_Performance_PK',
 'home_Performance_PKatt',
 'home_Performance_CrdY',
 'home_Performance_CrdR',
 'away_players_used',
 'away_Age',
 'away_Poss',
 'away_Per 90 Minutes_Gls',
 'away_Per 90 Minutes_Ast',
 'away_Performance_PK',
 'away_Performance_PKatt',
 'away_Performance_CrdY',
 'away_Performance_CrdR',
 'home_elo',
 'away_elo',
 'Temp_Moy_C',
 'Humidite_Moy_%',
 'Pluie_Tot_mm',
 'Neige_Tot_cm',
 'Vent_Moy_kmh',
 'Rafale_Max_kmh',
 'id_y',
 'home_manager_country',
 'home_manager_preferred_formation',
 'home_manager_profile',
 'home_manager_team_style',
 'home_manager_pressing_intensity',
 'home_manager_defensive_line',
 'home_manager_wins',
 'home_manager_draws',
 'home_manager_losses',
 'home_manager_win_pct',
 'home_manager_avg_goals_scored',
 'home_manager_avg_goals_conceded',
 'home_manager_avg_possession',
 'home_manager_avg_shots',
 'home_manager_avg_shots_on_target',
 'home_manager_avg_xg_for',
 'home_manager_avg_xg_against',
 'home_manager_avg_corners',
 'home_manager_avg_yellow_cards',
 'home_manager_avg_red_cards',
 'home_manager_avg_fouls',
 'home_manager_clean_sheet_pct',
 'home_manager_btts_pct',
 'home_manager_current_team_id',
 'home_manager_current_team_name',
 'away_manager_id',
 'away_manager_country',
 'away_manager_preferred_formation',
 'away_manager_profile',
 'away_manager_team_style',
 'away_manager_pressing_intensity',
 'away_manager_defensive_line',
 'away_manager_wins',
 'away_manager_draws',
 'away_manager_losses',
 'away_manager_win_pct',
 'away_manager_avg_goals_scored',
 'away_manager_avg_goals_conceded',
 'away_manager_avg_possession',
 'away_manager_avg_shots',
 'away_manager_avg_shots_on_target',
 'away_manager_avg_xg_for',
 'away_manager_avg_xg_against',
 'away_manager_avg_corners',
 'away_manager_avg_yellow_cards',
 'away_manager_avg_red_cards',
 'away_manager_avg_fouls',
 'away_manager_clean_sheet_pct',
 'away_manager_btts_pct',
 'away_manager_current_team_id',
 'away_manager_current_team_name',
 'avg_yellow_per_match',
 'avg_red_per_match',
 'avg_goals_per_match',
 'avg_fouls_per_match']

In [97]:
# ==========================================
# ÉTAPE 9.1 : Chargement & Fusion Historiques FDCU
# ==========================================


df_history = pd.concat([
        pd.read_csv("data/pl_fdcu_20_21.csv"),
        pd.read_csv("data/pl_fdcu_21_22.csv"),
        pd.read_csv("data/pl_fdcu_22_23.csv"),
        pd.read_csv("data/pl_fdcu_23_24.csv"),
        pd.read_csv("data/pl_fdcu24_25.csv"),
        pd.read_csv("data/pl_fdcu25_26.csv")
], ignore_index=True)

# Nettoyage date
df_history['Date'] = pd.to_datetime(df_history['Date'], format='%d/%m/%Y', errors='coerce').dt.normalize()
df_history = df_history.sort_values('Date').reset_index(drop=True)

# Mapping équipes
map_fdcu_dyn = {
    'Man United': 'Manchester United',
    'Ipswich': 'Ipswich Town',
    "Nott'm Forest": 'Nottingham Forest',
    'Newcastle': 'Newcastle United',
    'West Ham': 'West Ham United',
    'Leicester': 'Leicester City',
    'Brighton': 'Brighton & Hove Albion',
    'Man City': 'Manchester City',
    'Tottenham': 'Tottenham Hotspur',
    'Wolves': 'Wolverhampton',
    'Leeds': 'Leeds United'
}
df_history['HomeTeam'] = df_history['HomeTeam'].replace(map_fdcu_dyn)
df_history['AwayTeam'] = df_history['AwayTeam'].replace(map_fdcu_dyn)

print("✅ Historiques FDCU chargés")

✅ Historiques FDCU chargés

In [98]:
# ==========================================
# ÉTAPE 9.2 : Calcul des Dynamiques Temporelles
# ==========================================

df_history['home_rest_days'] = 7.0
df_history['away_rest_days'] = 7.0
df_history['home_points_last_5'] = 0.0
df_history['away_points_last_5'] = 0.0
df_history['h2h_home_win_pct'] = 0.5

team_last_match_date = {}
team_match_history = {team: [] for team in pd.concat([df_history['HomeTeam'], df_history['AwayTeam']]).unique()}
h2h_history = {}

print("⏳ Calcul des dynamiques temporelles...")

for index, row in df_history.iterrows():
    home = row['HomeTeam']
    away = row['AwayTeam']
    match_date = row['Date']
    
    # Fatigue
    if home in team_last_match_date:
        df_history.at[index, 'home_rest_days'] = (match_date - team_last_match_date[home]).days
    if away in team_last_match_date:
        df_history.at[index, 'away_rest_days'] = (match_date - team_last_match_date[away]).days
    team_last_match_date[home] = match_date
    team_last_match_date[away] = match_date

    # Forme
    home_past = team_match_history[home][-5:]
    away_past = team_match_history[away][-5:]
    df_history.at[index, 'home_points_last_5'] = sum(home_past) if len(home_past) > 0 else 0
    df_history.at[index, 'away_points_last_5'] = sum(away_past) if len(away_past) > 0 else 0
    
    result = row['FTR']
    if result == 'H':
        team_match_history[home].append(3)
        team_match_history[away].append(0)
    elif result == 'A':
        team_match_history[home].append(0)
        team_match_history[away].append(3)
    else:
        team_match_history[home].append(1)
        team_match_history[away].append(1)

    # Head-to-Head
    pair = tuple(sorted([home, away]))
    if pair not in h2h_history:
        h2h_history[pair] = []
    past_encounters = h2h_history[pair][-5:]
    if len(past_encounters) > 0:
        wins = sum(1 for encounter in past_encounters if encounter['winner'] == home)
        df_history.at[index, 'h2h_home_win_pct'] = wins / len(past_encounters)
    winner_name = home if result == 'H' else (away if result == 'A' else 'Draw')
    h2h_history[pair].append({'date': match_date, 'winner': winner_name})

print("✅ Dynamiques temporelles calculées")

C:\Users\MUEL\AppData\Local\Temp\ipykernel_13956\366174479.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_history['home_rest_days'] = 7.0
C:\Users\MUEL\AppData\Local\Temp\ipykernel_13956\366174479.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_history['away_rest_days'] = 7.0
C:\Users\MUEL\AppData\Local\Temp\ipykernel_13956\366174479.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_history['home_points_last_5'] = 0.0
C:\Users\MUEL\AppData\Local\Temp\ipykernel_13956\366174479.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_history['away_points_last_5'] = 0.0
C:\Users\MUEL\AppData\Local\Temp\ipykernel_13956\366174479.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_history['h2h_home_win_pct'] = 0.5

⏳ Calcul des dynamiques temporelles...
✅ Dynamiques temporelles calculées

In [99]:
pl_events["home_team"].unique()

<ArrowStringArray>
[     'Manchester United',           'Ipswich Town',      'Nottingham Forest',
                'Arsenal',                'Everton',       'Newcastle United',
        'West Ham United',              'Brentford',                'Chelsea',
         'Leicester City', 'Brighton & Hove Albion',      'Tottenham Hotspur',
        'Manchester City',         'Crystal Palace',            'Southampton',
                 'Fulham',            'Aston Villa',            'Bournemouth',
          'Wolverhampton',              'Liverpool',             'Sunderland',
           'Leeds United',                'Burnley']
Length: 23, dtype: str

In [100]:
# ==========================================
# ÉTAPE 9.3 : Super-Features + Fusion Finale
# ==========================================

# Derby
liste_derbies = [
    {"Aston Villa", "Birmingham City"}, {"West Ham United", "Millwall"},
    {"Arsenal", "Tottenham Hotspur"}, {"Liverpool", "Everton"},
    {"Manchester United", "Manchester City"}, {"Sheffield United", "Sheffield Wednesday"},
    {"Bristol City", "Bristol Rovers"}, {"Stoke City", "Port Vale"},
    {"Nottingham Forest", "Notts County"}, {"Arsenal", "Chelsea"},
    {"Chelsea", "Fulham"}, {"Newcastle United", "Sunderland"},
    {"Ipswich Town", "Norwich City"}, {"Portsmouth", "Southampton"},
    {"Blackburn Rovers", "Burnley"}, {"West Bromwich Albion", "Wolverhampton"},
    {"Arsenal", "Manchester United"}, {"Chelsea", "Leeds United"},
    {"Leeds United", "Manchester United"}, {"Liverpool", "Manchester United"},
    {"Liverpool", "Manchester City"}
]

def est_un_derby(home, away):
    return 1 if {home, away} in liste_derbies else 0

pl_events['is_derby'] = pl_events.apply(lambda row: est_un_derby(row['home_team'], row['away_team']), axis=1)

# Blessures
def calculer_diff_absences(json_string):
    if pd.isna(json_string):
        return 0
    try:
        clean_json = str(json_string).replace('""', '"')
        if clean_json.startswith('"') and clean_json.endswith('"'):
            clean_json = clean_json[1:-1]
        data = json.loads(clean_json)
        return len(data.get('home', [])) - len(data.get('away', []))
    except:
        return 0

print("🏥 Extraction des blessures...")
pl_events['diff_absences'] = pl_events['unavailable_players'].apply(calculer_diff_absences)

# Momentum
historique_momentum = {team: [] for team in pd.concat([pl_events['home_team'], pl_events['away_team']]).unique()}
pl_events['home_momentum'] = 0.0
pl_events['away_momentum'] = 0.0

print("📈 Calcul du Momentum...")
for index, row in pl_events.iterrows():
    home = row['home_team']
    away = row['away_team']
    past_home = historique_momentum[home][-5:]
    past_away = historique_momentum[away][-5:]
    pl_events.at[index, 'home_momentum'] = sum(past_home) if len(past_home) > 0 else 0
    pl_events.at[index, 'away_momentum'] = sum(past_away) if len(past_away) > 0 else 0
    if not pd.isna(row['home_score']) and not pd.isna(row['actual_home_xg']):
        historique_momentum[home].append(row['home_score'] - row['actual_home_xg'])
    if not pd.isna(row['away_score']) and not pd.isna(row['actual_away_xg']):
        historique_momentum[away].append(row['away_score'] - row['actual_away_xg'])

print("✅ Super-features calculées")

🏥 Extraction des blessures...
📈 Calcul du Momentum...
✅ Super-features calculées

In [101]:
pl_events[(pl_events["home_team"]=="Liverpool")&(pl_events["away_team"]=="Aston Villa")]

,id,home_team,away_team,date,home_score,away_score,actual_home_xg,actual_away_xg,home_team_obj_id,away_team_obj_id,...,referee_name,venue_id,venue_name,venue_city,season_id,unavailable_players,is_derby,diff_absences,home_momentum,away_momentum
105,160278,Liverpool,Aston Villa,2024-11-09,2.0,0.0,NaN,NaN,1,3,...,NaN,1,Anfield,Liverpool,336,"{""home"": [{""name"": ""Alisson"", ""status"": ""doubt...",0,0,0.00,0.00
476,97,Liverpool,Aston Villa,2025-11-02,2.0,0.0,1.19,0.41,1,3,...,Stuart Attwell,1,Anfield,Liverpool,337,"{""home"": [{""name"": ""Alisson"", ""status"": ""doubt...",0,0,-3.04,4.82

In [102]:
# ==========================================
# FUSION : Historiques + Super-Features
# ==========================================

# Dynamiques
df_history_merge = df_history[['Date', 'HomeTeam', 'AwayTeam', 'home_rest_days', 'away_rest_days',
                                'home_points_last_5', 'away_points_last_5', 'h2h_home_win_pct']]
df_history_merge = df_history_merge.rename(columns={'Date': 'date', 'HomeTeam': 'home_team', 'AwayTeam': 'away_team'})
df_history_merge['date'] = pd.to_datetime(df_history_merge['date']).dt.normalize()

final_df = pd.merge(final_df, df_history_merge,
    left_on=['date', 'home_team', 'away_team'],
    right_on=['date', 'home_team', 'away_team'], how='left')

# Super-Features
df_super = pl_events[['date', 'home_team', 'away_team', 'is_derby', 'diff_absences', 'home_momentum', 'away_momentum']]
# 1. Précaution indispensable : S'assurer que les deux colonnes sont bien au format datetime
df_super['date'] = pd.to_datetime(df_super['date']).dt.normalize()
final_df['date'] = pd.to_datetime(final_df['date']).dt.normalize()

# 2. Règle d'or de merge_asof : Les deux tableaux doivent OBLIGATOIREMENT être triés par la date
df_super = df_super.sort_values('date')
final_df = final_df.sort_values('date')

# 3. La fusion avec tolérance de +/- 1 jour
final_df = pd.merge_asof(
    final_df, 
    df_super,
    on='date',                        # La colonne sur laquelle on applique la tolérance
    by=['home_team', 'away_team'],    # Les colonnes qui doivent correspondre EXACTEMENT
    direction='nearest',              # Cherche la date la plus proche (avant ou après)
    tolerance=pd.Timedelta(days=1)    # La fameuse limite de +/- 1 jour
)
print("✅ Fusion complète terminée !")

✅ Fusion complète terminée !

In [103]:
final_df.head(10)

,id_x,home_team,away_team,date,home_score,away_score,actual_home_xg,actual_away_xg,home_team_obj_id,away_team_obj_id,...,avg_fouls_per_match,home_rest_days,away_rest_days,home_points_last_5,away_points_last_5,h2h_home_win_pct,is_derby,diff_absences,home_momentum,away_momentum
0,160173,Manchester United,Fulham,2024-08-16,1.0,0.0,NaN,NaN,17,6,...,21.1,89.0,89.0,7.0,5.0,0.6,0,2,0.0,0.0
1,160174,Ipswich Town,Liverpool,2024-08-17,0.0,2.0,NaN,NaN,200,1,...,22.3,7.0,90.0,0.0,8.0,0.5,0,0,0.0,0.0
2,160178,Nottingham Forest,Bournemouth,2024-08-17,1.0,1.0,NaN,NaN,15,2,...,22.0,90.0,90.0,6.0,6.0,0.0,0,0,0.0,0.0
3,160175,Arsenal,Wolverhampton,2024-08-17,2.0,0.0,NaN,NaN,18,1247,...,19.9,90.0,90.0,15.0,3.0,1.0,0,0,0.0,0.0
4,160176,Everton,Brighton & Hove Albion,2024-08-17,0.0,3.0,NaN,NaN,20,5,...,23.0,90.0,90.0,10.0,4.0,0.2,0,0,0.0,0.0
5,160177,Newcastle United,Southampton,2024-08-17,1.0,0.0,NaN,NaN,4,205,...,21.7,90.0,447.0,10.0,1.0,0.8,0,0,0.0,0.0
6,160179,West Ham United,Aston Villa,2024-08-17,1.0,2.0,NaN,NaN,8,3,...,20.8,90.0,90.0,4.0,5.0,0.4,0,0,0.0,0.0
7,160180,Brentford,Crystal Palace,2024-08-18,2.0,1.0,NaN,NaN,16,14,...,19.6,91.0,91.0,7.0,13.0,0.0,0,1,0.0,0.0
8,160181,Chelsea,Manchester City,2024-08-18,0.0,2.0,NaN,NaN,13,12,...,20.8,91.0,91.0,15.0,15.0,0.0,0,0,0.0,0.0
9,160182,Leicester City,Tottenham Hotspur,2024-08-19,1.0,1.0,NaN,NaN,221,9,...,21.7,449.0,92.0,5.0,6.0,0.2,0,-8,0.0,0.0

In [104]:
# Liste exhaustive incluant toutes les cotes pour ton analyse de colinéarité future
ml_columns = [
    # --- Pour se repérer ---
    'date', 'home_team', 'away_team', "attendance",
    
    # --- y : Full Time Away Goals and Full Time Home Goals ---
    'FTHG', 'FTAG',
    
    # --- TOUTES LES COTES (Match Opening & Closing) ---
    'PSH', 'PSD', 'PSA', 'MaxH', 'MaxD', 'MaxA', 'AvgH', 'AvgD', 'AvgA', 
    'P>2.5', 'P<2.5', 'Max>2.5', 'Max<2.5', 'Avg>2.5', 'Avg<2.5', 
    'AHh', 'PAHH', 'PAHA', 'MaxAHH', 'MaxAHA', 'AvgAHH', 'AvgAHA', 
    'PSCH', 'PSCD', 'PSCA', 'MaxCH', 'MaxCD', 'MaxCA', 'AvgCH', 'AvgCD', 'AvgCA', 
    'PC>2.5', 'PC<2.5', 'MaxC>2.5', 'MaxC<2.5', 'AvgC>2.5', 'AvgC<2.5', 
    'AHCh', 'PCAHH', 'PCAHA', 'MaxCAHH', 'MaxCAHA', 'AvgCAHH', 'AvgCAHA', 
    'BMGMH', 'BMGMD', 'BMGMA', 'BVH', 'BVD', 'BVA', 'CLH', 'CLD', 'CLA', 
    'LBH', 'LBD', 'LBA', 'BMGMCH', 'BMGMCD', 'BMGMCA', 'BVCH', 'BVCD', 'BVCA', 
    'CLCH', 'CLCD', 'CLCA', 'LBCH', 'LBCD', 'LBCA',

    # --- FORCE DES ÉQUIPES & STATS SAISONNIÈRES ---
    'home_elo', 'away_elo',
    'home_Age', 'home_Poss', 'home_Per 90 Minutes_Gls', 'home_Per 90 Minutes_Ast', 
    'home_Performance_PK', 'home_Performance_PKatt', 'home_Performance_CrdY', 'home_Performance_CrdR',
    'away_Age', 'away_Poss', 'away_Per 90 Minutes_Gls', 'away_Per 90 Minutes_Ast', 
    'away_Performance_PK', 'away_Performance_PKatt', 'away_Performance_CrdY', 'away_Performance_CrdR',

    # --- MÉTÉO ---
    'Temp_Moy_C', 'Humidite_Moy_%', 'Pluie_Tot_mm', 'Neige_Tot_cm', 
    'Vent_Moy_kmh', 'Rafale_Max_kmh',

    # --- PROFIL DES MANAGERS ---
    'home_manager_preferred_formation', 'home_manager_team_style', 
    'home_manager_pressing_intensity', 'home_manager_defensive_line', 
    'home_manager_win_pct', 'home_manager_avg_goals_scored', 'home_manager_avg_goals_conceded', 
    'home_manager_avg_possession', 'home_manager_avg_shots', 'home_manager_avg_shots_on_target', 
    'home_manager_avg_xg_for', 'home_manager_avg_xg_against', 'home_manager_avg_corners', 
    'home_manager_avg_yellow_cards', 'home_manager_avg_red_cards', 'home_manager_avg_fouls', 
    'home_manager_clean_sheet_pct', 'home_manager_btts_pct',
    
    'away_manager_preferred_formation', 'away_manager_team_style', 
    'away_manager_pressing_intensity', 'away_manager_defensive_line', 
    'away_manager_win_pct', 'away_manager_avg_goals_scored', 'away_manager_avg_goals_conceded', 
    'away_manager_avg_possession', 'away_manager_avg_shots', 'away_manager_avg_shots_on_target', 
    'away_manager_xg_for', 'away_manager_xg_against', 'away_manager_corners', 
    'away_manager_yellow_cards', 'away_manager_red_cards', 'away_manager_fouls', 
    'away_manager_clean_sheet_pct', 'away_manager_btts_pct',

    # --- ARBITRAGE ---
    'avg_yellow_per_match', 'avg_red_per_match', 'avg_goals_per_match', 'avg_fouls_per_match',

    # --- New Features ---
    'home_rest_days', 'away_rest_days', 'home_points_last_5', 'away_points_last_5',
    'h2h_home_win_pct', 'is_derby', 'diff_absences', 'home_momentum', 'away_momentum'
]

# Nettoyage final pour garder uniquement les colonnes présentes dans ton DataFrame
valid_columns = [col for col in ml_columns if col in final_df.columns]
df_ml = final_df[valid_columns].copy()

print(f"Dataset prêt. {len(df_ml.columns)} colonnes conservées.")

Dataset prêt. 141 colonnes conservées.

In [105]:
df_ml.head()

,date,home_team,away_team,attendance,FTHG,FTAG,PSH,PSD,PSA,MaxH,...,avg_fouls_per_match,home_rest_days,away_rest_days,home_points_last_5,away_points_last_5,h2h_home_win_pct,is_derby,diff_absences,home_momentum,away_momentum
0,2024-08-16,Manchester United,Fulham,73297.0,1,0,1.63,4.38,5.30,1.68,...,21.1,89.0,89.0,7.0,5.0,0.6,0,2,0.0,0.0
1,2024-08-17,Ipswich Town,Liverpool,30014.0,0,2,8.18,5.84,1.34,9.00,...,22.3,7.0,90.0,0.0,8.0,0.5,0,0,0.0,0.0
2,2024-08-17,Nottingham Forest,Bournemouth,29763.0,1,1,2.47,3.42,2.97,2.51,...,22.0,90.0,90.0,6.0,6.0,0.0,0,0,0.0,0.0
3,2024-08-17,Arsenal,Wolverhampton,60261.0,2,0,1.16,8.56,16.22,1.20,...,19.9,90.0,90.0,15.0,3.0,1.0,0,0,0.0,0.0
4,2024-08-17,Everton,Brighton & Hove Albion,39217.0,0,3,2.73,3.36,2.71,2.76,...,23.0,90.0,90.0,10.0,4.0,0.2,0,0,0.0,0.0

In [106]:
df_ml.to_csv("data/processed.csv")